/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.CAdminDivisionRecord;


/**
 * 全国地区表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CAdminDivision extends TableImpl<CAdminDivisionRecord> {

    private static final long serialVersionUID = -184192964;

    /**
     * The reference instance of <code>public.c_admin_division</code>
     */
    public static final CAdminDivision C_ADMIN_DIVISION = new CAdminDivision();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CAdminDivisionRecord> getRecordType() {
        return CAdminDivisionRecord.class;
    }

    /**
     * The column <code>public.c_admin_division.id</code>.
     */
    public final TableField<CAdminDivisionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.c_admin_division.province_code</code>. 省代码
     */
    public final TableField<CAdminDivisionRecord, Long> PROVINCE_CODE = createField("province_code", org.jooq.impl.SQLDataType.BIGINT, this, "省代码");

    /**
     * The column <code>public.c_admin_division.province_name</code>. 省名
     */
    public final TableField<CAdminDivisionRecord, String> PROVINCE_NAME = createField("province_name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "省名");

    /**
     * The column <code>public.c_admin_division.city_code</code>. 市代码
     */
    public final TableField<CAdminDivisionRecord, Long> CITY_CODE = createField("city_code", org.jooq.impl.SQLDataType.BIGINT, this, "市代码");

    /**
     * The column <code>public.c_admin_division.city_name</code>. 市名
     */
    public final TableField<CAdminDivisionRecord, String> CITY_NAME = createField("city_name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "市名");

    /**
     * The column <code>public.c_admin_division.county_code</code>. 区县代码
     */
    public final TableField<CAdminDivisionRecord, Long> COUNTY_CODE = createField("county_code", org.jooq.impl.SQLDataType.BIGINT, this, "区县代码");

    /**
     * The column <code>public.c_admin_division.county_name</code>. 区县名
     */
    public final TableField<CAdminDivisionRecord, String> COUNTY_NAME = createField("county_name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "区县名");

    /**
     * The column <code>public.c_admin_division.town_code</code>. 乡镇代码
     */
    public final TableField<CAdminDivisionRecord, Long> TOWN_CODE = createField("town_code", org.jooq.impl.SQLDataType.BIGINT, this, "乡镇代码");

    /**
     * The column <code>public.c_admin_division.town_name</code>. 乡镇名
     */
    public final TableField<CAdminDivisionRecord, String> TOWN_NAME = createField("town_name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "乡镇名");

    /**
     * The column <code>public.c_admin_division.village_code</code>. 村代码
     */
    public final TableField<CAdminDivisionRecord, Long> VILLAGE_CODE = createField("village_code", org.jooq.impl.SQLDataType.BIGINT, this, "村代码");

    /**
     * The column <code>public.c_admin_division.village_name</code>. 村名
     */
    public final TableField<CAdminDivisionRecord, String> VILLAGE_NAME = createField("village_name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "村名");

    /**
     * The column <code>public.c_admin_division.level</code>. 地区级别
     */
    public final TableField<CAdminDivisionRecord, Integer> LEVEL = createField("level", org.jooq.impl.SQLDataType.INTEGER, this, "地区级别");

    /**
     * The column <code>public.c_admin_division.city_town_classify_code</code>. 城市分类
     */
    public final TableField<CAdminDivisionRecord, Integer> CITY_TOWN_CLASSIFY_CODE = createField("city_town_classify_code", org.jooq.impl.SQLDataType.INTEGER, this, "城市分类");

    /**
     * Create a <code>public.c_admin_division</code> table reference
     */
    public CAdminDivision() {
        this(DSL.name("c_admin_division"), null);
    }

    /**
     * Create an aliased <code>public.c_admin_division</code> table reference
     */
    public CAdminDivision(String alias) {
        this(DSL.name(alias), C_ADMIN_DIVISION);
    }

    /**
     * Create an aliased <code>public.c_admin_division</code> table reference
     */
    public CAdminDivision(Name alias) {
        this(alias, C_ADMIN_DIVISION);
    }

    private CAdminDivision(Name alias, Table<CAdminDivisionRecord> aliased) {
        this(alias, aliased, null);
    }

    private CAdminDivision(Name alias, Table<CAdminDivisionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("全国地区表"));
    }

    public <O extends Record> CAdminDivision(Table<O> child, ForeignKey<O, CAdminDivisionRecord> key) {
        super(child, key, C_ADMIN_DIVISION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.C_ADMIN_DIVISION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CAdminDivisionRecord> getPrimaryKey() {
        return Keys.C_ADMIN_DIVISION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CAdminDivisionRecord>> getKeys() {
        return Arrays.<UniqueKey<CAdminDivisionRecord>>asList(Keys.C_ADMIN_DIVISION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CAdminDivision as(String alias) {
        return new CAdminDivision(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CAdminDivision as(Name alias) {
        return new CAdminDivision(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CAdminDivision rename(String name) {
        return new CAdminDivision(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CAdminDivision rename(Name name) {
        return new CAdminDivision(name, null);
    }
}
