/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TArmsRecord;


/**
 * 强军管理
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TArms extends TableImpl<TArmsRecord> {

    private static final long serialVersionUID = -713327377;

    /**
     * The reference instance of <code>public.t_arms</code>
     */
    public static final TArms T_ARMS = new TArms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TArmsRecord> getRecordType() {
        return TArmsRecord.class;
    }

    /**
     * The column <code>public.t_arms.id</code>.
     */
    public final TableField<TArmsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_arms.title</code>. 标题
     */
    public final TableField<TArmsRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(200), this, "标题");

    /**
     * The column <code>public.t_arms.attachment</code>. 附件
     */
    public final TableField<TArmsRecord, Long> ATTACHMENT = createField("attachment", org.jooq.impl.SQLDataType.BIGINT, this, "附件");

    /**
     * The column <code>public.t_arms.content</code>. 内容
     */
    public final TableField<TArmsRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB, this, "内容");

    /**
     * The column <code>public.t_arms.read_count</code>. 阅读量
     */
    public final TableField<TArmsRecord, Long> READ_COUNT = createField("read_count", org.jooq.impl.SQLDataType.BIGINT, this, "阅读量");

    /**
     * The column <code>public.t_arms.status</code>. 状态
     */
    public final TableField<TArmsRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_arms.create_user</code>. 创建人
     */
    public final TableField<TArmsRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_arms.create_time</code>. 创建时间
     */
    public final TableField<TArmsRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_arms.update_user</code>. 修改人
     */
    public final TableField<TArmsRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_arms.update_time</code>. 修改时间
     */
    public final TableField<TArmsRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_arms.flag</code>. 标识
     */
    public final TableField<TArmsRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_arms</code> table reference
     */
    public TArms() {
        this(DSL.name("t_arms"), null);
    }

    /**
     * Create an aliased <code>public.t_arms</code> table reference
     */
    public TArms(String alias) {
        this(DSL.name(alias), T_ARMS);
    }

    /**
     * Create an aliased <code>public.t_arms</code> table reference
     */
    public TArms(Name alias) {
        this(alias, T_ARMS);
    }

    private TArms(Name alias, Table<TArmsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TArms(Name alias, Table<TArmsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("强军管理"));
    }

    public <O extends Record> TArms(Table<O> child, ForeignKey<O, TArmsRecord> key) {
        super(child, key, T_ARMS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_ARMS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TArmsRecord> getPrimaryKey() {
        return Keys.PK_T_ARMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TArmsRecord>> getKeys() {
        return Arrays.<UniqueKey<TArmsRecord>>asList(Keys.PK_T_ARMS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArms as(String alias) {
        return new TArms(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArms as(Name alias) {
        return new TArms(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TArms rename(String name) {
        return new TArms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TArms rename(Name name) {
        return new TArms(name, null);
    }
}
