/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TEquipTypeRecord;


/**
 * 设备类型
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TEquipType extends TableImpl<TEquipTypeRecord> {

    private static final long serialVersionUID = 619060458;

    /**
     * The reference instance of <code>public.t_equip_type</code>
     */
    public static final TEquipType T_EQUIP_TYPE = new TEquipType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TEquipTypeRecord> getRecordType() {
        return TEquipTypeRecord.class;
    }

    /**
     * The column <code>public.t_equip_type.id</code>.
     */
    public final TableField<TEquipTypeRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_equip_type.name</code>. 名字
     */
    public final TableField<TEquipTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(200), this, "名字");

    /**
     * The column <code>public.t_equip_type.status</code>. 状态
     */
    public final TableField<TEquipTypeRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_equip_type.create_user</code>. 创建人
     */
    public final TableField<TEquipTypeRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_equip_type.create_time</code>. 创建时间
     */
    public final TableField<TEquipTypeRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_equip_type.update_user</code>. 修改人
     */
    public final TableField<TEquipTypeRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_equip_type.update_time</code>. 修改时间
     */
    public final TableField<TEquipTypeRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_equip_type.flag</code>. 标识
     */
    public final TableField<TEquipTypeRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_equip_type</code> table reference
     */
    public TEquipType() {
        this(DSL.name("t_equip_type"), null);
    }

    /**
     * Create an aliased <code>public.t_equip_type</code> table reference
     */
    public TEquipType(String alias) {
        this(DSL.name(alias), T_EQUIP_TYPE);
    }

    /**
     * Create an aliased <code>public.t_equip_type</code> table reference
     */
    public TEquipType(Name alias) {
        this(alias, T_EQUIP_TYPE);
    }

    private TEquipType(Name alias, Table<TEquipTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TEquipType(Name alias, Table<TEquipTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("设备类型"));
    }

    public <O extends Record> TEquipType(Table<O> child, ForeignKey<O, TEquipTypeRecord> key) {
        super(child, key, T_EQUIP_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_EQUIP_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TEquipTypeRecord> getPrimaryKey() {
        return Keys.PK_T_EQUIP_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TEquipTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<TEquipTypeRecord>>asList(Keys.PK_T_EQUIP_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipType as(String alias) {
        return new TEquipType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TEquipType as(Name alias) {
        return new TEquipType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TEquipType rename(String name) {
        return new TEquipType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TEquipType rename(Name name) {
        return new TEquipType(name, null);
    }
}
