/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TFileRecord;


/**
 * 文件
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFile extends TableImpl<TFileRecord> {

    private static final long serialVersionUID = 273242625;

    /**
     * The reference instance of <code>public.t_file</code>
     */
    public static final TFile T_FILE = new TFile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TFileRecord> getRecordType() {
        return TFileRecord.class;
    }

    /**
     * The column <code>public.t_file.id</code>.
     */
    public final TableField<TFileRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_file.name</code>. 名字
     */
    public final TableField<TFileRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(200), this, "名字");

    /**
     * The column <code>public.t_file.file_type</code>. 文件类型
     */
    public final TableField<TFileRecord, String> FILE_TYPE = createField("file_type", org.jooq.impl.SQLDataType.VARCHAR(200), this, "文件类型");

    /**
     * The column <code>public.t_file.file_url</code>.
     */
    public final TableField<TFileRecord, String> FILE_URL = createField("file_url", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.t_file.file_size</code>. 文件大小
     */
    public final TableField<TFileRecord, Long> FILE_SIZE = createField("file_size", org.jooq.impl.SQLDataType.BIGINT, this, "文件大小");

    /**
     * The column <code>public.t_file.status</code>. 状态
     */
    public final TableField<TFileRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_file.create_user</code>. 创建人
     */
    public final TableField<TFileRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_file.create_time</code>. 创建时间
     */
    public final TableField<TFileRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_file.update_user</code>. 修改人
     */
    public final TableField<TFileRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_file.update_time</code>. 修改时间
     */
    public final TableField<TFileRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_file.flag</code>. 标识
     */
    public final TableField<TFileRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_file</code> table reference
     */
    public TFile() {
        this(DSL.name("t_file"), null);
    }

    /**
     * Create an aliased <code>public.t_file</code> table reference
     */
    public TFile(String alias) {
        this(DSL.name(alias), T_FILE);
    }

    /**
     * Create an aliased <code>public.t_file</code> table reference
     */
    public TFile(Name alias) {
        this(alias, T_FILE);
    }

    private TFile(Name alias, Table<TFileRecord> aliased) {
        this(alias, aliased, null);
    }

    private TFile(Name alias, Table<TFileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("文件"));
    }

    public <O extends Record> TFile(Table<O> child, ForeignKey<O, TFileRecord> key) {
        super(child, key, T_FILE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_FILE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TFileRecord> getPrimaryKey() {
        return Keys.PK_T_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TFileRecord>> getKeys() {
        return Arrays.<UniqueKey<TFileRecord>>asList(Keys.PK_T_FILE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFile as(String alias) {
        return new TFile(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFile as(Name alias) {
        return new TFile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TFile rename(String name) {
        return new TFile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TFile rename(Name name) {
        return new TFile(name, null);
    }
}
