/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TIndustryRecord;


/**
 * 行业
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TIndustry extends TableImpl<TIndustryRecord> {

    private static final long serialVersionUID = -1964337832;

    /**
     * The reference instance of <code>public.t_industry</code>
     */
    public static final TIndustry T_INDUSTRY = new TIndustry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TIndustryRecord> getRecordType() {
        return TIndustryRecord.class;
    }

    /**
     * The column <code>public.t_industry.id</code>.
     */
    public final TableField<TIndustryRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_industry.name</code>. 标题
     */
    public final TableField<TIndustryRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(200), this, "标题");

    /**
     * The column <code>public.t_industry.status</code>. 状态
     */
    public final TableField<TIndustryRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_industry.create_user</code>. 创建人
     */
    public final TableField<TIndustryRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_industry.create_time</code>. 创建时间
     */
    public final TableField<TIndustryRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_industry.update_user</code>. 修改人
     */
    public final TableField<TIndustryRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_industry.update_time</code>. 修改时间
     */
    public final TableField<TIndustryRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_industry.flag</code>. 标识
     */
    public final TableField<TIndustryRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_industry</code> table reference
     */
    public TIndustry() {
        this(DSL.name("t_industry"), null);
    }

    /**
     * Create an aliased <code>public.t_industry</code> table reference
     */
    public TIndustry(String alias) {
        this(DSL.name(alias), T_INDUSTRY);
    }

    /**
     * Create an aliased <code>public.t_industry</code> table reference
     */
    public TIndustry(Name alias) {
        this(alias, T_INDUSTRY);
    }

    private TIndustry(Name alias, Table<TIndustryRecord> aliased) {
        this(alias, aliased, null);
    }

    private TIndustry(Name alias, Table<TIndustryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("行业"));
    }

    public <O extends Record> TIndustry(Table<O> child, ForeignKey<O, TIndustryRecord> key) {
        super(child, key, T_INDUSTRY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_INDUSTRY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TIndustryRecord> getPrimaryKey() {
        return Keys.PK_T_INDUSTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TIndustryRecord>> getKeys() {
        return Arrays.<UniqueKey<TIndustryRecord>>asList(Keys.PK_T_INDUSTRY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndustry as(String alias) {
        return new TIndustry(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndustry as(Name alias) {
        return new TIndustry(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TIndustry rename(String name) {
        return new TIndustry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TIndustry rename(Name name) {
        return new TIndustry(name, null);
    }
}
