/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TManagementRegulationAttachmentRecord;


/**
 * 管理规定-附件
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TManagementRegulationAttachment extends TableImpl<TManagementRegulationAttachmentRecord> {

    private static final long serialVersionUID = 2145817104;

    /**
     * The reference instance of <code>public.t_management_regulation_attachment</code>
     */
    public static final TManagementRegulationAttachment T_MANAGEMENT_REGULATION_ATTACHMENT = new TManagementRegulationAttachment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TManagementRegulationAttachmentRecord> getRecordType() {
        return TManagementRegulationAttachmentRecord.class;
    }

    /**
     * The column <code>public.t_management_regulation_attachment.id</code>.
     */
    public final TableField<TManagementRegulationAttachmentRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_management_regulation_attachment.management_regulation_attachment_id</code>. 管理规定
     */
    public final TableField<TManagementRegulationAttachmentRecord, Long> MANAGEMENT_REGULATION_ATTACHMENT_ID = createField("management_regulation_attachment_id", org.jooq.impl.SQLDataType.BIGINT, this, "管理规定");

    /**
     * The column <code>public.t_management_regulation_attachment.file_id</code>. 文件
     */
    public final TableField<TManagementRegulationAttachmentRecord, String> FILE_ID = createField("file_id", org.jooq.impl.SQLDataType.VARCHAR(200), this, "文件");

    /**
     * The column <code>public.t_management_regulation_attachment.status</code>. 状态
     */
    public final TableField<TManagementRegulationAttachmentRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_management_regulation_attachment.create_user</code>. 创建人
     */
    public final TableField<TManagementRegulationAttachmentRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_management_regulation_attachment.create_time</code>. 创建时间
     */
    public final TableField<TManagementRegulationAttachmentRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_management_regulation_attachment.update_user</code>. 修改人
     */
    public final TableField<TManagementRegulationAttachmentRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_management_regulation_attachment.update_time</code>. 修改时间
     */
    public final TableField<TManagementRegulationAttachmentRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_management_regulation_attachment.flag</code>. 标识
     */
    public final TableField<TManagementRegulationAttachmentRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_management_regulation_attachment</code> table reference
     */
    public TManagementRegulationAttachment() {
        this(DSL.name("t_management_regulation_attachment"), null);
    }

    /**
     * Create an aliased <code>public.t_management_regulation_attachment</code> table reference
     */
    public TManagementRegulationAttachment(String alias) {
        this(DSL.name(alias), T_MANAGEMENT_REGULATION_ATTACHMENT);
    }

    /**
     * Create an aliased <code>public.t_management_regulation_attachment</code> table reference
     */
    public TManagementRegulationAttachment(Name alias) {
        this(alias, T_MANAGEMENT_REGULATION_ATTACHMENT);
    }

    private TManagementRegulationAttachment(Name alias, Table<TManagementRegulationAttachmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TManagementRegulationAttachment(Name alias, Table<TManagementRegulationAttachmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("管理规定-附件"));
    }

    public <O extends Record> TManagementRegulationAttachment(Table<O> child, ForeignKey<O, TManagementRegulationAttachmentRecord> key) {
        super(child, key, T_MANAGEMENT_REGULATION_ATTACHMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_MANAGEMENT_REGULATION_ATTACHMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TManagementRegulationAttachmentRecord> getPrimaryKey() {
        return Keys.PK_T_MANAGEMENT_REGULATION_ATTACHMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TManagementRegulationAttachmentRecord>> getKeys() {
        return Arrays.<UniqueKey<TManagementRegulationAttachmentRecord>>asList(Keys.PK_T_MANAGEMENT_REGULATION_ATTACHMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationAttachment as(String alias) {
        return new TManagementRegulationAttachment(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationAttachment as(Name alias) {
        return new TManagementRegulationAttachment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TManagementRegulationAttachment rename(String name) {
        return new TManagementRegulationAttachment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TManagementRegulationAttachment rename(Name name) {
        return new TManagementRegulationAttachment(name, null);
    }
}
