/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TManagementRegulationRecord;


/**
 * 管理规定
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TManagementRegulation extends TableImpl<TManagementRegulationRecord> {

    private static final long serialVersionUID = -2134145685;

    /**
     * The reference instance of <code>public.t_management_regulation</code>
     */
    public static final TManagementRegulation T_MANAGEMENT_REGULATION = new TManagementRegulation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TManagementRegulationRecord> getRecordType() {
        return TManagementRegulationRecord.class;
    }

    /**
     * The column <code>public.t_management_regulation.id</code>.
     */
    public final TableField<TManagementRegulationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_management_regulation.title</code>. 标题
     */
    public final TableField<TManagementRegulationRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(200), this, "标题");

    /**
     * The column <code>public.t_management_regulation.depart_id</code>. 发布部门
     */
    public final TableField<TManagementRegulationRecord, Long> DEPART_ID = createField("depart_id", org.jooq.impl.SQLDataType.BIGINT, this, "发布部门");

    /**
     * The column <code>public.t_management_regulation.top</code>. 置顶
     */
    public final TableField<TManagementRegulationRecord, Boolean> TOP = createField("top", org.jooq.impl.SQLDataType.BOOLEAN, this, "置顶");

    /**
     * The column <code>public.t_management_regulation.content</code>. 内容
     */
    public final TableField<TManagementRegulationRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB, this, "内容");

    /**
     * The column <code>public.t_management_regulation.read_count</code>. 阅读量
     */
    public final TableField<TManagementRegulationRecord, Long> READ_COUNT = createField("read_count", org.jooq.impl.SQLDataType.BIGINT, this, "阅读量");

    /**
     * The column <code>public.t_management_regulation.status</code>. 状态
     */
    public final TableField<TManagementRegulationRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_management_regulation.create_user</code>. 创建人
     */
    public final TableField<TManagementRegulationRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_management_regulation.create_time</code>. 创建时间
     */
    public final TableField<TManagementRegulationRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_management_regulation.update_user</code>. 修改人
     */
    public final TableField<TManagementRegulationRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_management_regulation.update_time</code>. 修改时间
     */
    public final TableField<TManagementRegulationRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_management_regulation.flag</code>. 标识
     */
    public final TableField<TManagementRegulationRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_management_regulation</code> table reference
     */
    public TManagementRegulation() {
        this(DSL.name("t_management_regulation"), null);
    }

    /**
     * Create an aliased <code>public.t_management_regulation</code> table reference
     */
    public TManagementRegulation(String alias) {
        this(DSL.name(alias), T_MANAGEMENT_REGULATION);
    }

    /**
     * Create an aliased <code>public.t_management_regulation</code> table reference
     */
    public TManagementRegulation(Name alias) {
        this(alias, T_MANAGEMENT_REGULATION);
    }

    private TManagementRegulation(Name alias, Table<TManagementRegulationRecord> aliased) {
        this(alias, aliased, null);
    }

    private TManagementRegulation(Name alias, Table<TManagementRegulationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("管理规定"));
    }

    public <O extends Record> TManagementRegulation(Table<O> child, ForeignKey<O, TManagementRegulationRecord> key) {
        super(child, key, T_MANAGEMENT_REGULATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_MANAGEMENT_REGULATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TManagementRegulationRecord> getPrimaryKey() {
        return Keys.PK_T_MANAGEMENT_REGULATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TManagementRegulationRecord>> getKeys() {
        return Arrays.<UniqueKey<TManagementRegulationRecord>>asList(Keys.PK_T_MANAGEMENT_REGULATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulation as(String alias) {
        return new TManagementRegulation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulation as(Name alias) {
        return new TManagementRegulation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TManagementRegulation rename(String name) {
        return new TManagementRegulation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TManagementRegulation rename(Name name) {
        return new TManagementRegulation(name, null);
    }
}
