/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TMarketInformationAttachmentRecord;


/**
 * 市场信息-附件
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMarketInformationAttachment extends TableImpl<TMarketInformationAttachmentRecord> {

    private static final long serialVersionUID = -614580024;

    /**
     * The reference instance of <code>public.t_market_information_attachment</code>
     */
    public static final TMarketInformationAttachment T_MARKET_INFORMATION_ATTACHMENT = new TMarketInformationAttachment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TMarketInformationAttachmentRecord> getRecordType() {
        return TMarketInformationAttachmentRecord.class;
    }

    /**
     * The column <code>public.t_market_information_attachment.id</code>.
     */
    public final TableField<TMarketInformationAttachmentRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_market_information_attachment.market_information_id</code>. 市场信息
     */
    public final TableField<TMarketInformationAttachmentRecord, Long> MARKET_INFORMATION_ID = createField("market_information_id", org.jooq.impl.SQLDataType.BIGINT, this, "市场信息");

    /**
     * The column <code>public.t_market_information_attachment.file_id</code>. 文件
     */
    public final TableField<TMarketInformationAttachmentRecord, String> FILE_ID = createField("file_id", org.jooq.impl.SQLDataType.VARCHAR(200), this, "文件");

    /**
     * The column <code>public.t_market_information_attachment.status</code>. 状态
     */
    public final TableField<TMarketInformationAttachmentRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_market_information_attachment.create_user</code>. 创建人
     */
    public final TableField<TMarketInformationAttachmentRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_market_information_attachment.create_time</code>. 创建时间
     */
    public final TableField<TMarketInformationAttachmentRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_market_information_attachment.update_user</code>. 修改人
     */
    public final TableField<TMarketInformationAttachmentRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_market_information_attachment.update_time</code>. 修改时间
     */
    public final TableField<TMarketInformationAttachmentRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_market_information_attachment.flag</code>. 标识
     */
    public final TableField<TMarketInformationAttachmentRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_market_information_attachment</code> table reference
     */
    public TMarketInformationAttachment() {
        this(DSL.name("t_market_information_attachment"), null);
    }

    /**
     * Create an aliased <code>public.t_market_information_attachment</code> table reference
     */
    public TMarketInformationAttachment(String alias) {
        this(DSL.name(alias), T_MARKET_INFORMATION_ATTACHMENT);
    }

    /**
     * Create an aliased <code>public.t_market_information_attachment</code> table reference
     */
    public TMarketInformationAttachment(Name alias) {
        this(alias, T_MARKET_INFORMATION_ATTACHMENT);
    }

    private TMarketInformationAttachment(Name alias, Table<TMarketInformationAttachmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TMarketInformationAttachment(Name alias, Table<TMarketInformationAttachmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("市场信息-附件"));
    }

    public <O extends Record> TMarketInformationAttachment(Table<O> child, ForeignKey<O, TMarketInformationAttachmentRecord> key) {
        super(child, key, T_MARKET_INFORMATION_ATTACHMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_MARKET_INFORMATION_ATTACHMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TMarketInformationAttachmentRecord> getPrimaryKey() {
        return Keys.PK_T_MARKET_INFORMATION_ATTACHMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TMarketInformationAttachmentRecord>> getKeys() {
        return Arrays.<UniqueKey<TMarketInformationAttachmentRecord>>asList(Keys.PK_T_MARKET_INFORMATION_ATTACHMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMarketInformationAttachment as(String alias) {
        return new TMarketInformationAttachment(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMarketInformationAttachment as(Name alias) {
        return new TMarketInformationAttachment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TMarketInformationAttachment rename(String name) {
        return new TMarketInformationAttachment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TMarketInformationAttachment rename(Name name) {
        return new TMarketInformationAttachment(name, null);
    }
}
