/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TVehiclePickRecord;


/**
 * 客房预订
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVehiclePick extends TableImpl<TVehiclePickRecord> {

    private static final long serialVersionUID = 387843515;

    /**
     * The reference instance of <code>public.t_vehicle_pick</code>
     */
    public static final TVehiclePick T_VEHICLE_PICK = new TVehiclePick();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TVehiclePickRecord> getRecordType() {
        return TVehiclePickRecord.class;
    }

    /**
     * The column <code>public.t_vehicle_pick.id</code>.
     */
    public final TableField<TVehiclePickRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_vehicle_pick.name</code>. 房客姓名
     */
    public final TableField<TVehiclePickRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(200), this, "房客姓名");

    /**
     * The column <code>public.t_vehicle_pick.idnum</code>. 身份证
     */
    public final TableField<TVehiclePickRecord, String> IDNUM = createField("idnum", org.jooq.impl.SQLDataType.VARCHAR(200), this, "身份证");

    /**
     * The column <code>public.t_vehicle_pick.phone</code>. 电话号码
     */
    public final TableField<TVehiclePickRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(20), this, "电话号码");

    /**
     * The column <code>public.t_vehicle_pick.workers</code>. 工作单位
     */
    public final TableField<TVehiclePickRecord, String> WORKERS = createField("workers", org.jooq.impl.SQLDataType.VARCHAR(200), this, "工作单位");

    /**
     * The column <code>public.t_vehicle_pick.persons</code>. 乘客总数
     */
    public final TableField<TVehiclePickRecord, Integer> PERSONS = createField("persons", org.jooq.impl.SQLDataType.INTEGER, this, "乘客总数");

    /**
     * The column <code>public.t_vehicle_pick.departure_place</code>.
     */
    public final TableField<TVehiclePickRecord, String> DEPARTURE_PLACE = createField("departure_place", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.t_vehicle_pick.destination</code>.
     */
    public final TableField<TVehiclePickRecord, String> DESTINATION = createField("destination", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.t_vehicle_pick.vehicle_time</code>. 接送时间
     */
    public final TableField<TVehiclePickRecord, Timestamp> VEHICLE_TIME = createField("vehicle_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "接送时间");

    /**
     * The column <code>public.t_vehicle_pick.remark</code>. 备注
     */
    public final TableField<TVehiclePickRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR(200), this, "备注");

    /**
     * The column <code>public.t_vehicle_pick.status</code>. 状态
     */
    public final TableField<TVehiclePickRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_vehicle_pick.create_user</code>. 创建人
     */
    public final TableField<TVehiclePickRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_vehicle_pick.create_time</code>. 创建时间
     */
    public final TableField<TVehiclePickRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_vehicle_pick.update_user</code>. 修改人
     */
    public final TableField<TVehiclePickRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_vehicle_pick.update_time</code>. 修改时间
     */
    public final TableField<TVehiclePickRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_vehicle_pick.flag</code>. 标识
     */
    public final TableField<TVehiclePickRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_vehicle_pick</code> table reference
     */
    public TVehiclePick() {
        this(DSL.name("t_vehicle_pick"), null);
    }

    /**
     * Create an aliased <code>public.t_vehicle_pick</code> table reference
     */
    public TVehiclePick(String alias) {
        this(DSL.name(alias), T_VEHICLE_PICK);
    }

    /**
     * Create an aliased <code>public.t_vehicle_pick</code> table reference
     */
    public TVehiclePick(Name alias) {
        this(alias, T_VEHICLE_PICK);
    }

    private TVehiclePick(Name alias, Table<TVehiclePickRecord> aliased) {
        this(alias, aliased, null);
    }

    private TVehiclePick(Name alias, Table<TVehiclePickRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("客房预订"));
    }

    public <O extends Record> TVehiclePick(Table<O> child, ForeignKey<O, TVehiclePickRecord> key) {
        super(child, key, T_VEHICLE_PICK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_VEHICLE_PICK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TVehiclePickRecord> getPrimaryKey() {
        return Keys.PK_T_VEHICLE_PICK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TVehiclePickRecord>> getKeys() {
        return Arrays.<UniqueKey<TVehiclePickRecord>>asList(Keys.PK_T_VEHICLE_PICK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVehiclePick as(String alias) {
        return new TVehiclePick(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TVehiclePick as(Name alias) {
        return new TVehiclePick(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TVehiclePick rename(String name) {
        return new TVehiclePick(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TVehiclePick rename(Name name) {
        return new TVehiclePick(name, null);
    }
}
