/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TWorkDynamicsRecord;


/**
 * 工作动态
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWorkDynamics extends TableImpl<TWorkDynamicsRecord> {

    private static final long serialVersionUID = -999859813;

    /**
     * The reference instance of <code>public.t_work_dynamics</code>
     */
    public static final TWorkDynamics T_WORK_DYNAMICS = new TWorkDynamics();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TWorkDynamicsRecord> getRecordType() {
        return TWorkDynamicsRecord.class;
    }

    /**
     * The column <code>public.t_work_dynamics.id</code>.
     */
    public final TableField<TWorkDynamicsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_work_dynamics.title</code>. 标题
     */
    public final TableField<TWorkDynamicsRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(200), this, "标题");

    /**
     * The column <code>public.t_work_dynamics.abstract</code>. 摘要
     */
    public final TableField<TWorkDynamicsRecord, String> ABSTRACT = createField("abstract", org.jooq.impl.SQLDataType.VARCHAR(200), this, "摘要");

    /**
     * The column <code>public.t_work_dynamics.face</code>. 封面
     */
    public final TableField<TWorkDynamicsRecord, String> FACE = createField("face", org.jooq.impl.SQLDataType.VARCHAR(300), this, "封面");

    /**
     * The column <code>public.t_work_dynamics.top</code>. 置顶
     */
    public final TableField<TWorkDynamicsRecord, Boolean> TOP = createField("top", org.jooq.impl.SQLDataType.BOOLEAN, this, "置顶");

    /**
     * The column <code>public.t_work_dynamics.content</code>. 内容
     */
    public final TableField<TWorkDynamicsRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB, this, "内容");

    /**
     * The column <code>public.t_work_dynamics.read_count</code>. 阅读量
     */
    public final TableField<TWorkDynamicsRecord, Long> READ_COUNT = createField("read_count", org.jooq.impl.SQLDataType.BIGINT, this, "阅读量");

    /**
     * The column <code>public.t_work_dynamics.status</code>. 状态
     */
    public final TableField<TWorkDynamicsRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_work_dynamics.create_user</code>. 创建人
     */
    public final TableField<TWorkDynamicsRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_work_dynamics.create_time</code>. 创建时间
     */
    public final TableField<TWorkDynamicsRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_work_dynamics.update_user</code>. 修改人
     */
    public final TableField<TWorkDynamicsRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_work_dynamics.update_time</code>. 修改时间
     */
    public final TableField<TWorkDynamicsRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_work_dynamics.flag</code>. 标识
     */
    public final TableField<TWorkDynamicsRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_work_dynamics</code> table reference
     */
    public TWorkDynamics() {
        this(DSL.name("t_work_dynamics"), null);
    }

    /**
     * Create an aliased <code>public.t_work_dynamics</code> table reference
     */
    public TWorkDynamics(String alias) {
        this(DSL.name(alias), T_WORK_DYNAMICS);
    }

    /**
     * Create an aliased <code>public.t_work_dynamics</code> table reference
     */
    public TWorkDynamics(Name alias) {
        this(alias, T_WORK_DYNAMICS);
    }

    private TWorkDynamics(Name alias, Table<TWorkDynamicsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TWorkDynamics(Name alias, Table<TWorkDynamicsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("工作动态"));
    }

    public <O extends Record> TWorkDynamics(Table<O> child, ForeignKey<O, TWorkDynamicsRecord> key) {
        super(child, key, T_WORK_DYNAMICS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_WORK_DYNAMICS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TWorkDynamicsRecord> getPrimaryKey() {
        return Keys.PK_T_WORK_DYNAMICS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TWorkDynamicsRecord>> getKeys() {
        return Arrays.<UniqueKey<TWorkDynamicsRecord>>asList(Keys.PK_T_WORK_DYNAMICS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamics as(String alias) {
        return new TWorkDynamics(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamics as(Name alias) {
        return new TWorkDynamics(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TWorkDynamics rename(String name) {
        return new TWorkDynamics(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TWorkDynamics rename(Name name) {
        return new TWorkDynamics(name, null);
    }
}
