/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TWorkDynamicsAttachmentRecord;


/**
 * 质量通知公告-附件
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWorkDynamicsAttachment extends TableImpl<TWorkDynamicsAttachmentRecord> {

    private static final long serialVersionUID = -1739328998;

    /**
     * The reference instance of <code>public.t_work_dynamics_attachment</code>
     */
    public static final TWorkDynamicsAttachment T_WORK_DYNAMICS_ATTACHMENT = new TWorkDynamicsAttachment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TWorkDynamicsAttachmentRecord> getRecordType() {
        return TWorkDynamicsAttachmentRecord.class;
    }

    /**
     * The column <code>public.t_work_dynamics_attachment.id</code>.
     */
    public final TableField<TWorkDynamicsAttachmentRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_work_dynamics_attachment.work_dynamics_id</code>. 质量通知公告
     */
    public final TableField<TWorkDynamicsAttachmentRecord, Long> WORK_DYNAMICS_ID = createField("work_dynamics_id", org.jooq.impl.SQLDataType.BIGINT, this, "质量通知公告");

    /**
     * The column <code>public.t_work_dynamics_attachment.file_id</code>. 文件
     */
    public final TableField<TWorkDynamicsAttachmentRecord, String> FILE_ID = createField("file_id", org.jooq.impl.SQLDataType.VARCHAR(200), this, "文件");

    /**
     * The column <code>public.t_work_dynamics_attachment.status</code>. 状态
     */
    public final TableField<TWorkDynamicsAttachmentRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态");

    /**
     * The column <code>public.t_work_dynamics_attachment.create_user</code>. 创建人
     */
    public final TableField<TWorkDynamicsAttachmentRecord, Long> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.BIGINT, this, "创建人");

    /**
     * The column <code>public.t_work_dynamics_attachment.create_time</code>. 创建时间
     */
    public final TableField<TWorkDynamicsAttachmentRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>public.t_work_dynamics_attachment.update_user</code>. 修改人
     */
    public final TableField<TWorkDynamicsAttachmentRecord, Long> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.BIGINT, this, "修改人");

    /**
     * The column <code>public.t_work_dynamics_attachment.update_time</code>. 修改时间
     */
    public final TableField<TWorkDynamicsAttachmentRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>public.t_work_dynamics_attachment.flag</code>. 标识
     */
    public final TableField<TWorkDynamicsAttachmentRecord, Boolean> FLAG = createField("flag", org.jooq.impl.SQLDataType.BOOLEAN, this, "标识");

    /**
     * Create a <code>public.t_work_dynamics_attachment</code> table reference
     */
    public TWorkDynamicsAttachment() {
        this(DSL.name("t_work_dynamics_attachment"), null);
    }

    /**
     * Create an aliased <code>public.t_work_dynamics_attachment</code> table reference
     */
    public TWorkDynamicsAttachment(String alias) {
        this(DSL.name(alias), T_WORK_DYNAMICS_ATTACHMENT);
    }

    /**
     * Create an aliased <code>public.t_work_dynamics_attachment</code> table reference
     */
    public TWorkDynamicsAttachment(Name alias) {
        this(alias, T_WORK_DYNAMICS_ATTACHMENT);
    }

    private TWorkDynamicsAttachment(Name alias, Table<TWorkDynamicsAttachmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TWorkDynamicsAttachment(Name alias, Table<TWorkDynamicsAttachmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("质量通知公告-附件"));
    }

    public <O extends Record> TWorkDynamicsAttachment(Table<O> child, ForeignKey<O, TWorkDynamicsAttachmentRecord> key) {
        super(child, key, T_WORK_DYNAMICS_ATTACHMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_T_WORK_DYNAMICS_ATTACHMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TWorkDynamicsAttachmentRecord> getPrimaryKey() {
        return Keys.PK_T_WORK_DYNAMICS_ATTACHMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TWorkDynamicsAttachmentRecord>> getKeys() {
        return Arrays.<UniqueKey<TWorkDynamicsAttachmentRecord>>asList(Keys.PK_T_WORK_DYNAMICS_ATTACHMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsAttachment as(String alias) {
        return new TWorkDynamicsAttachment(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsAttachment as(Name alias) {
        return new TWorkDynamicsAttachment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TWorkDynamicsAttachment rename(String name) {
        return new TWorkDynamicsAttachment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TWorkDynamicsAttachment rename(Name name) {
        return new TWorkDynamicsAttachment(name, null);
    }
}
