spring:
  devtools: true
  flyway:
    locations: classpath:/db_migrations
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.55.102:5432/id_platform?searchpath=public
    username: postgres
    password: postgres
    maxLifetime: 0
    maxPoolSize: 500
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 100Mb
  redis:
    database: 4
    host: 192.168.55.105
    index: 15
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5
  jooq:
    sql-dialect: POSTGRES

logging:
  level:
    org:
      jooq: debug

hdfs:
  ip: 192.168.55.115
  port: 8020
  filePath: /tempFiles/

upload.dir: /uploadfiles

web:
  localPath: /opt/tempfile/



sms:
  appid: 1400160235
  appkey: 3f3a7ad476daf923402d41964cffe1dd
  smsSign: 清数科技
  codeTemplateid: 225961  #发送验证码模板id
  replayReportTemplateid: 225956 #回复举报模板id
  addReportTemplateid: 225959 #添加举报模板id
