/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TDataDownload;


/**
 * 资料下载
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDataDownloadRecord extends UpdatableRecordImpl<TDataDownloadRecord> implements Record11<Long, String, String, Integer, Integer, Long, Timestamp, Long, Timestamp, Boolean, String> {

    private static final long serialVersionUID = 1541326480;

    /**
     * Setter for <code>public.t_data_download.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_data_download.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_data_download.report_name</code>. 资料名称
     */
    public void setReportName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_data_download.report_name</code>. 资料名称
     */
    public String getReportName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_data_download.subject_id</code>. 学科
     */
    public void setSubjectId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_data_download.subject_id</code>. 学科
     */
    public String getSubjectId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_data_download.downloads</code>. 下载量
     */
    public void setDownloads(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_data_download.downloads</code>. 下载量
     */
    public Integer getDownloads() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.t_data_download.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_data_download.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.t_data_download.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_data_download.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.t_data_download.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_data_download.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.t_data_download.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_data_download.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.t_data_download.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_data_download.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>public.t_data_download.flag</code>. 标识
     */
    public void setFlag(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_data_download.flag</code>. 标识
     */
    public Boolean getFlag() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.t_data_download.file_url</code>. 附件
     */
    public void setFileUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_data_download.file_url</code>. 附件
     */
    public String getFileUrl() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Integer, Integer, Long, Timestamp, Long, Timestamp, Boolean, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Integer, Integer, Long, Timestamp, Long, Timestamp, Boolean, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TDataDownload.T_DATA_DOWNLOAD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TDataDownload.T_DATA_DOWNLOAD.REPORT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TDataDownload.T_DATA_DOWNLOAD.SUBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TDataDownload.T_DATA_DOWNLOAD.DOWNLOADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TDataDownload.T_DATA_DOWNLOAD.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return TDataDownload.T_DATA_DOWNLOAD.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TDataDownload.T_DATA_DOWNLOAD.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return TDataDownload.T_DATA_DOWNLOAD.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TDataDownload.T_DATA_DOWNLOAD.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return TDataDownload.T_DATA_DOWNLOAD.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TDataDownload.T_DATA_DOWNLOAD.FILE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReportName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSubjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReportName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSubjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value2(String value) {
        setReportName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value3(String value) {
        setSubjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value4(Integer value) {
        setDownloads(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value6(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value8(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value9(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value10(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord value11(String value) {
        setFileUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDataDownloadRecord values(Long value1, String value2, String value3, Integer value4, Integer value5, Long value6, Timestamp value7, Long value8, Timestamp value9, Boolean value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDataDownloadRecord
     */
    public TDataDownloadRecord() {
        super(TDataDownload.T_DATA_DOWNLOAD);
    }

    /**
     * Create a detached, initialised TDataDownloadRecord
     */
    public TDataDownloadRecord(Long id, String reportName, String subjectId, Integer downloads, Integer status, Long createUser, Timestamp createTime, Long updateUser, Timestamp updateTime, Boolean flag, String fileUrl) {
        super(TDataDownload.T_DATA_DOWNLOAD);

        set(0, id);
        set(1, reportName);
        set(2, subjectId);
        set(3, downloads);
        set(4, status);
        set(5, createUser);
        set(6, createTime);
        set(7, updateUser);
        set(8, updateTime);
        set(9, flag);
        set(10, fileUrl);
    }
}
