/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TDepart;


/**
 * 部门
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDepartRecord extends UpdatableRecordImpl<TDepartRecord> implements Record8<Long, String, Integer, Timestamp, Timestamp, Long, Long, Boolean> {

    private static final long serialVersionUID = 1081876426;

    /**
     * Setter for <code>public.t_depart.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_depart.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_depart.name</code>. 名字
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_depart.name</code>. 名字
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_depart.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_depart.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.t_depart.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_depart.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.t_depart.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_depart.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.t_depart.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_depart.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.t_depart.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_depart.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.t_depart.flag</code>. 标记
     */
    public void setFlag(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_depart.flag</code>. 标记
     */
    public Boolean getFlag() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Integer, Timestamp, Timestamp, Long, Long, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Integer, Timestamp, Timestamp, Long, Long, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TDepart.T_DEPART.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TDepart.T_DEPART.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TDepart.T_DEPART.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TDepart.T_DEPART.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TDepart.T_DEPART.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return TDepart.T_DEPART.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TDepart.T_DEPART.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return TDepart.T_DEPART.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDepartRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDepartRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDepartRecord value3(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDepartRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDepartRecord value5(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDepartRecord value6(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDepartRecord value7(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDepartRecord value8(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDepartRecord values(Long value1, String value2, Integer value3, Timestamp value4, Timestamp value5, Long value6, Long value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDepartRecord
     */
    public TDepartRecord() {
        super(TDepart.T_DEPART);
    }

    /**
     * Create a detached, initialised TDepartRecord
     */
    public TDepartRecord(Long id, String name, Integer status, Timestamp createTime, Timestamp updateTime, Long createUser, Long updateUser, Boolean flag) {
        super(TDepart.T_DEPART);

        set(0, id);
        set(1, name);
        set(2, status);
        set(3, createTime);
        set(4, updateTime);
        set(5, createUser);
        set(6, updateUser);
        set(7, flag);
    }
}
