/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TDivision;


/**
 * 区划表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDivisionRecord extends UpdatableRecordImpl<TDivisionRecord> implements Record8<Long, Long, String, String, Long, Short, Long, Long> {

    private static final long serialVersionUID = -465647502;

    /**
     * Setter for <code>public.t_division.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_division.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_division.code</code>. 行政区划代码
     */
    public void setCode(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_division.code</code>. 行政区划代码
     */
    public Long getCode() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.t_division.name</code>. 名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_division.name</code>. 名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_division.full_name</code>. 完整名称
     */
    public void setFullName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_division.full_name</code>. 完整名称
     */
    public String getFullName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_division.parent_id</code>. 父级id
     */
    public void setParentId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_division.parent_id</code>. 父级id
     */
    public Long getParentId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.t_division.level</code>. 层级
     */
    public void setLevel(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_division.level</code>. 层级
     */
    public Short getLevel() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.t_division.district_id</code>. 区县id
     */
    public void setDistrictId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_division.district_id</code>. 区县id
     */
    public Long getDistrictId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.t_division.town_id</code>. 乡镇ID
     */
    public void setTownId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_division.town_id</code>. 乡镇ID
     */
    public Long getTownId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, String, Long, Short, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, String, Long, Short, Long, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TDivision.T_DIVISION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TDivision.T_DIVISION.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TDivision.T_DIVISION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TDivision.T_DIVISION.FULL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return TDivision.T_DIVISION.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return TDivision.T_DIVISION.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TDivision.T_DIVISION.DISTRICT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return TDivision.T_DIVISION.TOWN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component6() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getDistrictId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getTownId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getDistrictId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getTownId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDivisionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDivisionRecord value2(Long value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDivisionRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDivisionRecord value4(String value) {
        setFullName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDivisionRecord value5(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDivisionRecord value6(Short value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDivisionRecord value7(Long value) {
        setDistrictId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDivisionRecord value8(Long value) {
        setTownId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDivisionRecord values(Long value1, Long value2, String value3, String value4, Long value5, Short value6, Long value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDivisionRecord
     */
    public TDivisionRecord() {
        super(TDivision.T_DIVISION);
    }

    /**
     * Create a detached, initialised TDivisionRecord
     */
    public TDivisionRecord(Long id, Long code, String name, String fullName, Long parentId, Short level, Long districtId, Long townId) {
        super(TDivision.T_DIVISION);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, fullName);
        set(4, parentId);
        set(5, level);
        set(6, districtId);
        set(7, townId);
    }
}
