/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TManagementRegulation;


/**
 * 管理规定
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TManagementRegulationRecord extends UpdatableRecordImpl<TManagementRegulationRecord> implements Record12<Long, String, Long, Boolean, String, Long, Integer, Long, Timestamp, Long, Timestamp, Boolean> {

    private static final long serialVersionUID = -82173020;

    /**
     * Setter for <code>public.t_management_regulation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_management_regulation.title</code>. 标题
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_management_regulation.depart_id</code>. 发布部门
     */
    public void setDepartId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.depart_id</code>. 发布部门
     */
    public Long getDepartId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.t_management_regulation.top</code>. 置顶
     */
    public void setTop(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.top</code>. 置顶
     */
    public Boolean getTop() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.t_management_regulation.content</code>. 内容
     */
    public void setContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.content</code>. 内容
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.t_management_regulation.read_count</code>. 阅读量
     */
    public void setReadCount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.read_count</code>. 阅读量
     */
    public Long getReadCount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.t_management_regulation.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.t_management_regulation.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.t_management_regulation.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>public.t_management_regulation.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.t_management_regulation.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>public.t_management_regulation.flag</code>. 标识
     */
    public void setFlag(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_management_regulation.flag</code>. 标识
     */
    public Boolean getFlag() {
        return (Boolean) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, Long, Boolean, String, Long, Integer, Long, Timestamp, Long, Timestamp, Boolean> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, Long, Boolean, String, Long, Integer, Long, Timestamp, Long, Timestamp, Boolean> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.DEPART_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.TOP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.READ_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return TManagementRegulation.T_MANAGEMENT_REGULATION.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getDepartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getTop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getReadCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getDepartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getTop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getReadCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value3(Long value) {
        setDepartId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value4(Boolean value) {
        setTop(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value5(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value6(Long value) {
        setReadCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value7(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value8(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value10(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord value12(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TManagementRegulationRecord values(Long value1, String value2, Long value3, Boolean value4, String value5, Long value6, Integer value7, Long value8, Timestamp value9, Long value10, Timestamp value11, Boolean value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TManagementRegulationRecord
     */
    public TManagementRegulationRecord() {
        super(TManagementRegulation.T_MANAGEMENT_REGULATION);
    }

    /**
     * Create a detached, initialised TManagementRegulationRecord
     */
    public TManagementRegulationRecord(Long id, String title, Long departId, Boolean top, String content, Long readCount, Integer status, Long createUser, Timestamp createTime, Long updateUser, Timestamp updateTime, Boolean flag) {
        super(TManagementRegulation.T_MANAGEMENT_REGULATION);

        set(0, id);
        set(1, title);
        set(2, departId);
        set(3, top);
        set(4, content);
        set(5, readCount);
        set(6, status);
        set(7, createUser);
        set(8, createTime);
        set(9, updateUser);
        set(10, updateTime);
        set(11, flag);
    }
}
