/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TOrderingMeals;


/**
 * 网上订餐
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderingMealsRecord extends UpdatableRecordImpl<TOrderingMealsRecord> implements Record14<Long, String, String, String, String, Integer, Timestamp, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> {

    private static final long serialVersionUID = 1181417080;

    /**
     * Setter for <code>public.t_ordering_meals.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_ordering_meals.name</code>. 用餐人姓名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.name</code>. 用餐人姓名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_ordering_meals.idnum</code>. 身份证
     */
    public void setIdnum(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.idnum</code>. 身份证
     */
    public String getIdnum() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_ordering_meals.phone</code>. 联系电话
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.phone</code>. 联系电话
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_ordering_meals.workers</code>. 工作单位
     */
    public void setWorkers(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.workers</code>. 工作单位
     */
    public String getWorkers() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.t_ordering_meals.eats_count</code>. 用餐人数
     */
    public void setEatsCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.eats_count</code>. 用餐人数
     */
    public Integer getEatsCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.t_ordering_meals.eat_time</code>. 用餐时间
     */
    public void setEatTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.eat_time</code>. 用餐时间
     */
    public Timestamp getEatTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.t_ordering_meals.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.t_ordering_meals.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.t_ordering_meals.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.t_ordering_meals.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>public.t_ordering_meals.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.t_ordering_meals.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>public.t_ordering_meals.flag</code>. 标识
     */
    public void setFlag(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.t_ordering_meals.flag</code>. 标识
     */
    public Boolean getFlag() {
        return (Boolean) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, Integer, Timestamp, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, Integer, Timestamp, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TOrderingMeals.T_ORDERING_MEALS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TOrderingMeals.T_ORDERING_MEALS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TOrderingMeals.T_ORDERING_MEALS.IDNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TOrderingMeals.T_ORDERING_MEALS.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TOrderingMeals.T_ORDERING_MEALS.WORKERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TOrderingMeals.T_ORDERING_MEALS.EATS_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TOrderingMeals.T_ORDERING_MEALS.EAT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TOrderingMeals.T_ORDERING_MEALS.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TOrderingMeals.T_ORDERING_MEALS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return TOrderingMeals.T_ORDERING_MEALS.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TOrderingMeals.T_ORDERING_MEALS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return TOrderingMeals.T_ORDERING_MEALS.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return TOrderingMeals.T_ORDERING_MEALS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return TOrderingMeals.T_ORDERING_MEALS.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIdnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWorkers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getEatsCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getEatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIdnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWorkers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getEatsCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getEatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value3(String value) {
        setIdnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value5(String value) {
        setWorkers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value6(Integer value) {
        setEatsCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value7(Timestamp value) {
        setEatTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value8(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value10(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value11(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value12(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value13(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord value14(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderingMealsRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6, Timestamp value7, String value8, Integer value9, Long value10, Timestamp value11, Long value12, Timestamp value13, Boolean value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TOrderingMealsRecord
     */
    public TOrderingMealsRecord() {
        super(TOrderingMeals.T_ORDERING_MEALS);
    }

    /**
     * Create a detached, initialised TOrderingMealsRecord
     */
    public TOrderingMealsRecord(Long id, String name, String idnum, String phone, String workers, Integer eatsCount, Timestamp eatTime, String remark, Integer status, Long createUser, Timestamp createTime, Long updateUser, Timestamp updateTime, Boolean flag) {
        super(TOrderingMeals.T_ORDERING_MEALS);

        set(0, id);
        set(1, name);
        set(2, idnum);
        set(3, phone);
        set(4, workers);
        set(5, eatsCount);
        set(6, eatTime);
        set(7, remark);
        set(8, status);
        set(9, createUser);
        set(10, createTime);
        set(11, updateUser);
        set(12, updateTime);
        set(13, flag);
    }
}
