/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TQualityEvent;


/**
 * 质量事件
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TQualityEventRecord extends UpdatableRecordImpl<TQualityEventRecord> implements Record16<Long, String, Long, Long, String, Timestamp, Integer, String, Boolean, Integer, Long, Timestamp, Long, Timestamp, Boolean, String> {

    private static final long serialVersionUID = -1535968914;

    /**
     * Setter for <code>public.t_quality_event.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_quality_event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_quality_event.name</code>. 事件名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_quality_event.name</code>. 事件名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_quality_event.event_level</code>. 事件级别
     */
    public void setEventLevel(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_quality_event.event_level</code>. 事件级别
     */
    public Long getEventLevel() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.t_quality_event.supplier_id</code>. 供应商
     */
    public void setSupplierId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_quality_event.supplier_id</code>. 供应商
     */
    public Long getSupplierId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.t_quality_event.materials</code>. 涉及物料
     */
    public void setMaterials(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_quality_event.materials</code>. 涉及物料
     */
    public String getMaterials() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.t_quality_event.occurrence_time</code>. 发生时间
     */
    public void setOccurrenceTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_quality_event.occurrence_time</code>. 发生时间
     */
    public Timestamp getOccurrenceTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.t_quality_event.depart_id</code>. 发生部门
     */
    public void setDepartId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_quality_event.depart_id</code>. 发生部门
     */
    public Integer getDepartId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.t_quality_event.remark</code>. 事件描述
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_quality_event.remark</code>. 事件描述
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.t_quality_event.top</code>. 置顶
     */
    public void setTop(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_quality_event.top</code>. 置顶
     */
    public Boolean getTop() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.t_quality_event.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_quality_event.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.t_quality_event.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_quality_event.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.t_quality_event.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_quality_event.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>public.t_quality_event.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_quality_event.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.t_quality_event.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.t_quality_event.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>public.t_quality_event.flag</code>. 标识
     */
    public void setFlag(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.t_quality_event.flag</code>. 标识
     */
    public Boolean getFlag() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.t_quality_event.file_url</code>. 文件
     */
    public void setFileUrl(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.t_quality_event.file_url</code>. 文件
     */
    public String getFileUrl() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, Long, Long, String, Timestamp, Integer, String, Boolean, Integer, Long, Timestamp, Long, Timestamp, Boolean, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, Long, Long, String, Timestamp, Integer, String, Boolean, Integer, Long, Timestamp, Long, Timestamp, Boolean, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TQualityEvent.T_QUALITY_EVENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TQualityEvent.T_QUALITY_EVENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return TQualityEvent.T_QUALITY_EVENT.EVENT_LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return TQualityEvent.T_QUALITY_EVENT.SUPPLIER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TQualityEvent.T_QUALITY_EVENT.MATERIALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TQualityEvent.T_QUALITY_EVENT.OCCURRENCE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TQualityEvent.T_QUALITY_EVENT.DEPART_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TQualityEvent.T_QUALITY_EVENT.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return TQualityEvent.T_QUALITY_EVENT.TOP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return TQualityEvent.T_QUALITY_EVENT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return TQualityEvent.T_QUALITY_EVENT.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return TQualityEvent.T_QUALITY_EVENT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return TQualityEvent.T_QUALITY_EVENT.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return TQualityEvent.T_QUALITY_EVENT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field15() {
        return TQualityEvent.T_QUALITY_EVENT.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return TQualityEvent.T_QUALITY_EVENT.FILE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getEventLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getSupplierId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMaterials();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getOccurrenceTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getDepartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getTop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component15() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getEventLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getSupplierId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMaterials();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getOccurrenceTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDepartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getTop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value15() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value3(Long value) {
        setEventLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value4(Long value) {
        setSupplierId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value5(String value) {
        setMaterials(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value6(Timestamp value) {
        setOccurrenceTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value7(Integer value) {
        setDepartId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value8(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value9(Boolean value) {
        setTop(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value10(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value11(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value12(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value13(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value14(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value15(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord value16(String value) {
        setFileUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQualityEventRecord values(Long value1, String value2, Long value3, Long value4, String value5, Timestamp value6, Integer value7, String value8, Boolean value9, Integer value10, Long value11, Timestamp value12, Long value13, Timestamp value14, Boolean value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TQualityEventRecord
     */
    public TQualityEventRecord() {
        super(TQualityEvent.T_QUALITY_EVENT);
    }

    /**
     * Create a detached, initialised TQualityEventRecord
     */
    public TQualityEventRecord(Long id, String name, Long eventLevel, Long supplierId, String materials, Timestamp occurrenceTime, Integer departId, String remark, Boolean top, Integer status, Long createUser, Timestamp createTime, Long updateUser, Timestamp updateTime, Boolean flag, String fileUrl) {
        super(TQualityEvent.T_QUALITY_EVENT);

        set(0, id);
        set(1, name);
        set(2, eventLevel);
        set(3, supplierId);
        set(4, materials);
        set(5, occurrenceTime);
        set(6, departId);
        set(7, remark);
        set(8, top);
        set(9, status);
        set(10, createUser);
        set(11, createTime);
        set(12, updateUser);
        set(13, updateTime);
        set(14, flag);
        set(15, fileUrl);
    }
}
