/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TReports;


/**
 * 投诉举报
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TReportsRecord extends UpdatableRecordImpl<TReportsRecord> implements Record15<Long, String, String, String, String, Timestamp, Timestamp, Integer, Long, Timestamp, Long, Timestamp, Boolean, String, String> {

    private static final long serialVersionUID = -544903724;

    /**
     * Setter for <code>public.t_reports.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_reports.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_reports.report_name</code>.
     */
    public void setReportName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_reports.report_name</code>.
     */
    public String getReportName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_reports.works</code>.
     */
    public void setWorks(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_reports.works</code>.
     */
    public String getWorks() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_reports.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_reports.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_reports.title</code>.
     */
    public void setTitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_reports.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.t_reports.report_time</code>.
     */
    public void setReportTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_reports.report_time</code>.
     */
    public Timestamp getReportTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.t_reports.deal_time</code>.
     */
    public void setDealTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_reports.deal_time</code>.
     */
    public Timestamp getDealTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.t_reports.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_reports.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.t_reports.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_reports.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.t_reports.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_reports.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.t_reports.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_reports.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.t_reports.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_reports.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>public.t_reports.flag</code>. 标识
     */
    public void setFlag(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_reports.flag</code>. 标识
     */
    public Boolean getFlag() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.t_reports.content</code>. 举报内容
     */
    public void setContent(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.t_reports.content</code>. 举报内容
     */
    public String getContent() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.t_reports.suggestion</code>. 处理意见
     */
    public void setSuggestion(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.t_reports.suggestion</code>. 处理意见
     */
    public String getSuggestion() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, String, String, String, String, Timestamp, Timestamp, Integer, Long, Timestamp, Long, Timestamp, Boolean, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, String, String, String, String, Timestamp, Timestamp, Integer, Long, Timestamp, Long, Timestamp, Boolean, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TReports.T_REPORTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TReports.T_REPORTS.REPORT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TReports.T_REPORTS.WORKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TReports.T_REPORTS.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TReports.T_REPORTS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TReports.T_REPORTS.REPORT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TReports.T_REPORTS.DEAL_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TReports.T_REPORTS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return TReports.T_REPORTS.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TReports.T_REPORTS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return TReports.T_REPORTS.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return TReports.T_REPORTS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return TReports.T_REPORTS.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TReports.T_REPORTS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TReports.T_REPORTS.SUGGESTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReportName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWorks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getReportTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDealTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component13() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getSuggestion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReportName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWorks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getReportTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDealTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getSuggestion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value2(String value) {
        setReportName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value3(String value) {
        setWorks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value5(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value6(Timestamp value) {
        setReportTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value7(Timestamp value) {
        setDealTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value8(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value9(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value10(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value11(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value12(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value13(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value14(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord value15(String value) {
        setSuggestion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReportsRecord values(Long value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, Integer value8, Long value9, Timestamp value10, Long value11, Timestamp value12, Boolean value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TReportsRecord
     */
    public TReportsRecord() {
        super(TReports.T_REPORTS);
    }

    /**
     * Create a detached, initialised TReportsRecord
     */
    public TReportsRecord(Long id, String reportName, String works, String phone, String title, Timestamp reportTime, Timestamp dealTime, Integer status, Long createUser, Timestamp createTime, Long updateUser, Timestamp updateTime, Boolean flag, String content, String suggestion) {
        super(TReports.T_REPORTS);

        set(0, id);
        set(1, reportName);
        set(2, works);
        set(3, phone);
        set(4, title);
        set(5, reportTime);
        set(6, dealTime);
        set(7, status);
        set(8, createUser);
        set(9, createTime);
        set(10, updateUser);
        set(11, updateTime);
        set(12, flag);
        set(13, content);
        set(14, suggestion);
    }
}
