/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TRoomReservation;


/**
 * 客房预订
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoomReservationRecord extends UpdatableRecordImpl<TRoomReservationRecord> implements Record14<Long, String, String, String, Integer, Integer, Timestamp, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> {

    private static final long serialVersionUID = -1546316685;

    /**
     * Setter for <code>public.t_room_reservation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_room_reservation.name</code>. 房客姓名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.name</code>. 房客姓名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_room_reservation.idnum</code>. 身份证
     */
    public void setIdnum(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.idnum</code>. 身份证
     */
    public String getIdnum() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_room_reservation.workers</code>. 工作单位
     */
    public void setWorkers(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.workers</code>. 工作单位
     */
    public String getWorkers() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_room_reservation.persons</code>. 入住人数
     */
    public void setPersons(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.persons</code>. 入住人数
     */
    public Integer getPersons() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.t_room_reservation.rooms</code>. 预订房间数
     */
    public void setRooms(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.rooms</code>. 预订房间数
     */
    public Integer getRooms() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.t_room_reservation.living_time</code>. 入住时间
     */
    public void setLivingTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.living_time</code>. 入住时间
     */
    public Timestamp getLivingTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.t_room_reservation.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.t_room_reservation.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.t_room_reservation.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.t_room_reservation.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>public.t_room_reservation.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.t_room_reservation.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>public.t_room_reservation.flag</code>. 标识
     */
    public void setFlag(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.t_room_reservation.flag</code>. 标识
     */
    public Boolean getFlag() {
        return (Boolean) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, Integer, Integer, Timestamp, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, Integer, Integer, Timestamp, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TRoomReservation.T_ROOM_RESERVATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TRoomReservation.T_ROOM_RESERVATION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TRoomReservation.T_ROOM_RESERVATION.IDNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRoomReservation.T_ROOM_RESERVATION.WORKERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TRoomReservation.T_ROOM_RESERVATION.PERSONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TRoomReservation.T_ROOM_RESERVATION.ROOMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TRoomReservation.T_ROOM_RESERVATION.LIVING_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TRoomReservation.T_ROOM_RESERVATION.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TRoomReservation.T_ROOM_RESERVATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return TRoomReservation.T_ROOM_RESERVATION.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TRoomReservation.T_ROOM_RESERVATION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return TRoomReservation.T_ROOM_RESERVATION.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return TRoomReservation.T_ROOM_RESERVATION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return TRoomReservation.T_ROOM_RESERVATION.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIdnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getWorkers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getPersons();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getRooms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getLivingTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIdnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getWorkers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPersons();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getRooms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLivingTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value3(String value) {
        setIdnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value4(String value) {
        setWorkers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value5(Integer value) {
        setPersons(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value6(Integer value) {
        setRooms(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value7(Timestamp value) {
        setLivingTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value8(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value10(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value11(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value12(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value13(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord value14(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoomReservationRecord values(Long value1, String value2, String value3, String value4, Integer value5, Integer value6, Timestamp value7, String value8, Integer value9, Long value10, Timestamp value11, Long value12, Timestamp value13, Boolean value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRoomReservationRecord
     */
    public TRoomReservationRecord() {
        super(TRoomReservation.T_ROOM_RESERVATION);
    }

    /**
     * Create a detached, initialised TRoomReservationRecord
     */
    public TRoomReservationRecord(Long id, String name, String idnum, String workers, Integer persons, Integer rooms, Timestamp livingTime, String remark, Integer status, Long createUser, Timestamp createTime, Long updateUser, Timestamp updateTime, Boolean flag) {
        super(TRoomReservation.T_ROOM_RESERVATION);

        set(0, id);
        set(1, name);
        set(2, idnum);
        set(3, workers);
        set(4, persons);
        set(5, rooms);
        set(6, livingTime);
        set(7, remark);
        set(8, status);
        set(9, createUser);
        set(10, createTime);
        set(11, updateUser);
        set(12, updateTime);
        set(13, flag);
    }
}
