/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TSupplier;


/**
 * 供应商
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSupplierRecord extends UpdatableRecordImpl<TSupplierRecord> implements Record20<Long, String, Long, String, String, String, Timestamp, String, String, String, String, String, Long, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> {

    private static final long serialVersionUID = 1488685215;

    /**
     * Setter for <code>public.t_supplier.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_supplier.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_supplier.name</code>. 标题
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_supplier.name</code>. 标题
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_supplier.type</code>. 摘要
     */
    public void setType(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_supplier.type</code>. 摘要
     */
    public Long getType() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.t_supplier.region</code>. 封面
     */
    public void setRegion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_supplier.region</code>. 封面
     */
    public String getRegion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_supplier.address</code>. 置顶
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_supplier.address</code>. 置顶
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.t_supplier.social_credit_code</code>. 内容
     */
    public void setSocialCreditCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_supplier.social_credit_code</code>. 内容
     */
    public String getSocialCreditCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.t_supplier.regist_date</code>. 阅读量
     */
    public void setRegistDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_supplier.regist_date</code>. 阅读量
     */
    public Timestamp getRegistDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.t_supplier.legal_person</code>.
     */
    public void setLegalPerson(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_supplier.legal_person</code>.
     */
    public String getLegalPerson() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.t_supplier.legal_person_name</code>.
     */
    public void setLegalPersonName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_supplier.legal_person_name</code>.
     */
    public String getLegalPersonName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.t_supplier.contacts_user_name</code>.
     */
    public void setContactsUserName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_supplier.contacts_user_name</code>.
     */
    public String getContactsUserName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.t_supplier.contacts_use_idnum</code>.
     */
    public void setContactsUseIdnum(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_supplier.contacts_use_idnum</code>.
     */
    public String getContactsUseIdnum() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.t_supplier.phone</code>.
     */
    public void setPhone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_supplier.phone</code>.
     */
    public String getPhone() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.t_supplier.logo</code>.
     */
    public void setLogo(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_supplier.logo</code>.
     */
    public Long getLogo() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.t_supplier.remark</code>.
     */
    public void setRemark(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.t_supplier.remark</code>.
     */
    public String getRemark() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.t_supplier.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.t_supplier.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.t_supplier.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.t_supplier.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.t_supplier.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.t_supplier.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>public.t_supplier.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.t_supplier.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.t_supplier.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.t_supplier.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>public.t_supplier.flag</code>. 标识
     */
    public void setFlag(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.t_supplier.flag</code>. 标识
     */
    public Boolean getFlag() {
        return (Boolean) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, String, Long, String, String, String, Timestamp, String, String, String, String, String, Long, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, String, Long, String, String, String, Timestamp, String, String, String, String, String, Long, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TSupplier.T_SUPPLIER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TSupplier.T_SUPPLIER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return TSupplier.T_SUPPLIER.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TSupplier.T_SUPPLIER.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TSupplier.T_SUPPLIER.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TSupplier.T_SUPPLIER.SOCIAL_CREDIT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TSupplier.T_SUPPLIER.REGIST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TSupplier.T_SUPPLIER.LEGAL_PERSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TSupplier.T_SUPPLIER.LEGAL_PERSON_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TSupplier.T_SUPPLIER.CONTACTS_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TSupplier.T_SUPPLIER.CONTACTS_USE_IDNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TSupplier.T_SUPPLIER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return TSupplier.T_SUPPLIER.LOGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TSupplier.T_SUPPLIER.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return TSupplier.T_SUPPLIER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return TSupplier.T_SUPPLIER.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return TSupplier.T_SUPPLIER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return TSupplier.T_SUPPLIER.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field19() {
        return TSupplier.T_SUPPLIER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field20() {
        return TSupplier.T_SUPPLIER.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSocialCreditCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getRegistDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLegalPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLegalPersonName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getContactsUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getContactsUseIdnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component16() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component18() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component19() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component20() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSocialCreditCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getRegistDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLegalPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLegalPersonName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getContactsUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getContactsUseIdnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value19() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value20() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value3(Long value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value4(String value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value5(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value6(String value) {
        setSocialCreditCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value7(Timestamp value) {
        setRegistDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value8(String value) {
        setLegalPerson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value9(String value) {
        setLegalPersonName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value10(String value) {
        setContactsUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value11(String value) {
        setContactsUseIdnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value12(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value13(Long value) {
        setLogo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value14(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value15(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value16(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value17(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value18(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value19(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord value20(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSupplierRecord values(Long value1, String value2, Long value3, String value4, String value5, String value6, Timestamp value7, String value8, String value9, String value10, String value11, String value12, Long value13, String value14, Integer value15, Long value16, Timestamp value17, Long value18, Timestamp value19, Boolean value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSupplierRecord
     */
    public TSupplierRecord() {
        super(TSupplier.T_SUPPLIER);
    }

    /**
     * Create a detached, initialised TSupplierRecord
     */
    public TSupplierRecord(Long id, String name, Long type, String region, String address, String socialCreditCode, Timestamp registDate, String legalPerson, String legalPersonName, String contactsUserName, String contactsUseIdnum, String phone, Long logo, String remark, Integer status, Long createUser, Timestamp createTime, Long updateUser, Timestamp updateTime, Boolean flag) {
        super(TSupplier.T_SUPPLIER);

        set(0, id);
        set(1, name);
        set(2, type);
        set(3, region);
        set(4, address);
        set(5, socialCreditCode);
        set(6, registDate);
        set(7, legalPerson);
        set(8, legalPersonName);
        set(9, contactsUserName);
        set(10, contactsUseIdnum);
        set(11, phone);
        set(12, logo);
        set(13, remark);
        set(14, status);
        set(15, createUser);
        set(16, createTime);
        set(17, updateUser);
        set(18, updateTime);
        set(19, flag);
    }
}
