/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TTenderOrgation;


/**
 * 投标机构
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTenderOrgationRecord extends UpdatableRecordImpl<TTenderOrgationRecord> implements Record20<Long, String, String, String, String, String, Timestamp, String, String, String, String, String, Long, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> {

    private static final long serialVersionUID = -1606368800;

    /**
     * Setter for <code>public.t_tender_orgation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_tender_orgation.code</code>. 机构编码
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.code</code>. 机构编码
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_tender_orgation.name</code>. 机构名字
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.name</code>. 机构名字
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_tender_orgation.region</code>. 所在地区
     */
    public void setRegion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.region</code>. 所在地区
     */
    public String getRegion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_tender_orgation.address</code>. 详细地址
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.address</code>. 详细地址
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.t_tender_orgation.social_credit_code</code>. 统一社会信用代码
     */
    public void setSocialCreditCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.social_credit_code</code>. 统一社会信用代码
     */
    public String getSocialCreditCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.t_tender_orgation.regist_date</code>. 注册日期
     */
    public void setRegistDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.regist_date</code>. 注册日期
     */
    public Timestamp getRegistDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.t_tender_orgation.legal_person</code>. 法人姓名
     */
    public void setLegalPerson(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.legal_person</code>. 法人姓名
     */
    public String getLegalPerson() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.t_tender_orgation.legal_person_name</code>. 法人身份证
     */
    public void setLegalPersonName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.legal_person_name</code>. 法人身份证
     */
    public String getLegalPersonName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.t_tender_orgation.contacts_user_name</code>. 联系人姓名
     */
    public void setContactsUserName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.contacts_user_name</code>. 联系人姓名
     */
    public String getContactsUserName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.t_tender_orgation.contacts_use_idnum</code>. 联系人身份证
     */
    public void setContactsUseIdnum(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.contacts_use_idnum</code>. 联系人身份证
     */
    public String getContactsUseIdnum() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.t_tender_orgation.phone</code>. 联系电话
     */
    public void setPhone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.phone</code>. 联系电话
     */
    public String getPhone() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.t_tender_orgation.grade</code>. 评级
     */
    public void setGrade(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.grade</code>. 评级
     */
    public Long getGrade() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.t_tender_orgation.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.t_tender_orgation.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.t_tender_orgation.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.t_tender_orgation.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>public.t_tender_orgation.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.t_tender_orgation.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>public.t_tender_orgation.flag</code>. 标识
     */
    public void setFlag(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.t_tender_orgation.flag</code>. 标识
     */
    public Boolean getFlag() {
        return (Boolean) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, String, String, String, String, String, Timestamp, String, String, String, String, String, Long, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, String, String, String, String, String, Timestamp, String, String, String, String, String, Long, String, Integer, Long, Timestamp, Long, Timestamp, Boolean> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TTenderOrgation.T_TENDER_ORGATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TTenderOrgation.T_TENDER_ORGATION.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TTenderOrgation.T_TENDER_ORGATION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TTenderOrgation.T_TENDER_ORGATION.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TTenderOrgation.T_TENDER_ORGATION.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TTenderOrgation.T_TENDER_ORGATION.SOCIAL_CREDIT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TTenderOrgation.T_TENDER_ORGATION.REGIST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TTenderOrgation.T_TENDER_ORGATION.LEGAL_PERSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TTenderOrgation.T_TENDER_ORGATION.LEGAL_PERSON_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TTenderOrgation.T_TENDER_ORGATION.CONTACTS_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TTenderOrgation.T_TENDER_ORGATION.CONTACTS_USE_IDNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TTenderOrgation.T_TENDER_ORGATION.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return TTenderOrgation.T_TENDER_ORGATION.GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TTenderOrgation.T_TENDER_ORGATION.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return TTenderOrgation.T_TENDER_ORGATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return TTenderOrgation.T_TENDER_ORGATION.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return TTenderOrgation.T_TENDER_ORGATION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return TTenderOrgation.T_TENDER_ORGATION.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field19() {
        return TTenderOrgation.T_TENDER_ORGATION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field20() {
        return TTenderOrgation.T_TENDER_ORGATION.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSocialCreditCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getRegistDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLegalPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLegalPersonName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getContactsUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getContactsUseIdnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component16() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component18() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component19() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component20() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSocialCreditCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getRegistDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLegalPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLegalPersonName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getContactsUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getContactsUseIdnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value19() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value20() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value4(String value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value5(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value6(String value) {
        setSocialCreditCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value7(Timestamp value) {
        setRegistDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value8(String value) {
        setLegalPerson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value9(String value) {
        setLegalPersonName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value10(String value) {
        setContactsUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value11(String value) {
        setContactsUseIdnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value12(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value13(Long value) {
        setGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value14(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value15(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value16(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value17(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value18(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value19(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord value20(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTenderOrgationRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, String value8, String value9, String value10, String value11, String value12, Long value13, String value14, Integer value15, Long value16, Timestamp value17, Long value18, Timestamp value19, Boolean value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TTenderOrgationRecord
     */
    public TTenderOrgationRecord() {
        super(TTenderOrgation.T_TENDER_ORGATION);
    }

    /**
     * Create a detached, initialised TTenderOrgationRecord
     */
    public TTenderOrgationRecord(Long id, String code, String name, String region, String address, String socialCreditCode, Timestamp registDate, String legalPerson, String legalPersonName, String contactsUserName, String contactsUseIdnum, String phone, Long grade, String remark, Integer status, Long createUser, Timestamp createTime, Long updateUser, Timestamp updateTime, Boolean flag) {
        super(TTenderOrgation.T_TENDER_ORGATION);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, region);
        set(4, address);
        set(5, socialCreditCode);
        set(6, registDate);
        set(7, legalPerson);
        set(8, legalPersonName);
        set(9, contactsUserName);
        set(10, contactsUseIdnum);
        set(11, phone);
        set(12, grade);
        set(13, remark);
        set(14, status);
        set(15, createUser);
        set(16, createTime);
        set(17, updateUser);
        set(18, updateTime);
        set(19, flag);
    }
}
