/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TUser;


/**
 * 用户
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRecord extends UpdatableRecordImpl<TUserRecord> implements Record14<Long, Long, String, String, Long, String, String, String, Integer, Timestamp, Timestamp, Long, Long, Boolean> {

    private static final long serialVersionUID = 1918024065;

    /**
     * Setter for <code>public.t_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_user.depart_id</code>.
     */
    public void setDepartId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_user.depart_id</code>.
     */
    public Long getDepartId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.t_user.phone</code>. 电话
     */
    public void setPhone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_user.phone</code>. 电话
     */
    public String getPhone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_user.name</code>. 名字
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_user.name</code>. 名字
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_user.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_user.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.t_user.login_name</code>. 用户名
     */
    public void setLoginName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_user.login_name</code>. 用户名
     */
    public String getLoginName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.t_user.password</code>. 密码
     */
    public void setPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_user.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.t_user.remark</code>.
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_user.remark</code>.
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.t_user.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_user.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.t_user.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_user.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.t_user.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_user.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>public.t_user.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_user.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.t_user.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_user.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.t_user.flag</code>. 标记
     */
    public void setFlag(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.t_user.flag</code>. 标记
     */
    public Boolean getFlag() {
        return (Boolean) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, String, String, Long, String, String, String, Integer, Timestamp, Timestamp, Long, Long, Boolean> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, String, String, Long, String, String, String, Integer, Timestamp, Timestamp, Long, Long, Boolean> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TUser.T_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TUser.T_USER.DEPART_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TUser.T_USER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TUser.T_USER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return TUser.T_USER.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TUser.T_USER.LOGIN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TUser.T_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TUser.T_USER.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TUser.T_USER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TUser.T_USER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TUser.T_USER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return TUser.T_USER.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return TUser.T_USER.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return TUser.T_USER.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getDepartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLoginName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getDepartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLoginName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value2(Long value) {
        setDepartId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value3(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value5(Long value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value6(String value) {
        setLoginName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value7(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value8(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value10(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value12(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value13(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value14(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord values(Long value1, Long value2, String value3, String value4, Long value5, String value6, String value7, String value8, Integer value9, Timestamp value10, Timestamp value11, Long value12, Long value13, Boolean value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserRecord
     */
    public TUserRecord() {
        super(TUser.T_USER);
    }

    /**
     * Create a detached, initialised TUserRecord
     */
    public TUserRecord(Long id, Long departId, String phone, String name, Long roleId, String loginName, String password, String remark, Integer status, Timestamp createTime, Timestamp updateTime, Long createUser, Long updateUser, Boolean flag) {
        super(TUser.T_USER);

        set(0, id);
        set(1, departId);
        set(2, phone);
        set(3, name);
        set(4, roleId);
        set(5, loginName);
        set(6, password);
        set(7, remark);
        set(8, status);
        set(9, createTime);
        set(10, updateTime);
        set(11, createUser);
        set(12, updateUser);
        set(13, flag);
    }
}
