/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.jooq.tables.TWorkDynamics;


/**
 * 工作动态
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWorkDynamicsRecord extends UpdatableRecordImpl<TWorkDynamicsRecord> implements Record13<Long, String, String, String, Boolean, String, Long, Integer, Long, Timestamp, Long, Timestamp, Boolean> {

    private static final long serialVersionUID = 324034152;

    /**
     * Setter for <code>public.t_work_dynamics.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_work_dynamics.title</code>. 标题
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_work_dynamics.abstract</code>. 摘要
     */
    public void setAbstract(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.abstract</code>. 摘要
     */
    public String getAbstract() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_work_dynamics.face</code>. 封面
     */
    public void setFace(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.face</code>. 封面
     */
    public String getFace() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_work_dynamics.top</code>. 置顶
     */
    public void setTop(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.top</code>. 置顶
     */
    public Boolean getTop() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.t_work_dynamics.content</code>. 内容
     */
    public void setContent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.content</code>. 内容
     */
    public String getContent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.t_work_dynamics.read_count</code>. 阅读量
     */
    public void setReadCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.read_count</code>. 阅读量
     */
    public Long getReadCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.t_work_dynamics.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.t_work_dynamics.create_user</code>. 创建人
     */
    public void setCreateUser(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.create_user</code>. 创建人
     */
    public Long getCreateUser() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.t_work_dynamics.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.t_work_dynamics.update_user</code>. 修改人
     */
    public void setUpdateUser(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.update_user</code>. 修改人
     */
    public Long getUpdateUser() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.t_work_dynamics.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>public.t_work_dynamics.flag</code>. 标识
     */
    public void setFlag(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_work_dynamics.flag</code>. 标识
     */
    public Boolean getFlag() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, Boolean, String, Long, Integer, Long, Timestamp, Long, Timestamp, Boolean> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, Boolean, String, Long, Integer, Long, Timestamp, Long, Timestamp, Boolean> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TWorkDynamics.T_WORK_DYNAMICS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TWorkDynamics.T_WORK_DYNAMICS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TWorkDynamics.T_WORK_DYNAMICS.ABSTRACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TWorkDynamics.T_WORK_DYNAMICS.FACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return TWorkDynamics.T_WORK_DYNAMICS.TOP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TWorkDynamics.T_WORK_DYNAMICS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TWorkDynamics.T_WORK_DYNAMICS.READ_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TWorkDynamics.T_WORK_DYNAMICS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return TWorkDynamics.T_WORK_DYNAMICS.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TWorkDynamics.T_WORK_DYNAMICS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return TWorkDynamics.T_WORK_DYNAMICS.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return TWorkDynamics.T_WORK_DYNAMICS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return TWorkDynamics.T_WORK_DYNAMICS.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAbstract();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getTop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getReadCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component13() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAbstract();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getTop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getReadCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value3(String value) {
        setAbstract(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value4(String value) {
        setFace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value5(Boolean value) {
        setTop(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value6(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value7(Long value) {
        setReadCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value8(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value9(Long value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value10(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value11(Long value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value12(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord value13(Boolean value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWorkDynamicsRecord values(Long value1, String value2, String value3, String value4, Boolean value5, String value6, Long value7, Integer value8, Long value9, Timestamp value10, Long value11, Timestamp value12, Boolean value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TWorkDynamicsRecord
     */
    public TWorkDynamicsRecord() {
        super(TWorkDynamics.T_WORK_DYNAMICS);
    }

    /**
     * Create a detached, initialised TWorkDynamicsRecord
     */
    public TWorkDynamicsRecord(Long id, String title, String abstract_, String face, Boolean top, String content, Long readCount, Integer status, Long createUser, Timestamp createTime, Long updateUser, Timestamp updateTime, Boolean flag) {
        super(TWorkDynamics.T_WORK_DYNAMICS);

        set(0, id);
        set(1, title);
        set(2, abstract_);
        set(3, face);
        set(4, top);
        set(5, content);
        set(6, readCount);
        set(7, status);
        set(8, createUser);
        set(9, createTime);
        set(10, updateUser);
        set(11, updateTime);
        set(12, flag);
    }
}
