/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.poem.jooq.tables.CAdminDivision;
import org.poem.jooq.tables.FlywaySchemaHistory;
import org.poem.jooq.tables.TArms;
import org.poem.jooq.tables.TArmsAttachment;
import org.poem.jooq.tables.TDataDownload;
import org.poem.jooq.tables.TDepart;
import org.poem.jooq.tables.TDivision;
import org.poem.jooq.tables.TEquipType;
import org.poem.jooq.tables.TEquipment;
import org.poem.jooq.tables.TFile;
import org.poem.jooq.tables.TIndustry;
import org.poem.jooq.tables.TLink;
import org.poem.jooq.tables.TManagementRegulation;
import org.poem.jooq.tables.TManagementRegulationAttachment;
import org.poem.jooq.tables.TMarketInformation;
import org.poem.jooq.tables.TMarketInformationAttachment;
import org.poem.jooq.tables.TMessage;
import org.poem.jooq.tables.TNews;
import org.poem.jooq.tables.TNewsAttachment;
import org.poem.jooq.tables.TNotice;
import org.poem.jooq.tables.TNoticeAttachment;
import org.poem.jooq.tables.TOrderingMeals;
import org.poem.jooq.tables.TParty;
import org.poem.jooq.tables.TPartyAttachment;
import org.poem.jooq.tables.TQualityDeal;
import org.poem.jooq.tables.TQualityEvent;
import org.poem.jooq.tables.TQualityNotice;
import org.poem.jooq.tables.TQualityNoticeAttachment;
import org.poem.jooq.tables.TReports;
import org.poem.jooq.tables.TRole;
import org.poem.jooq.tables.TRoomReservation;
import org.poem.jooq.tables.TSubject;
import org.poem.jooq.tables.TSupplier;
import org.poem.jooq.tables.TSupplierType;
import org.poem.jooq.tables.TSystemNotice;
import org.poem.jooq.tables.TSystemlog;
import org.poem.jooq.tables.TTenderOrgation;
import org.poem.jooq.tables.TUser;
import org.poem.jooq.tables.TVehiclePick;
import org.poem.jooq.tables.TWorkDynamics;
import org.poem.jooq.tables.TWorkDynamicsAttachment;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index C_ADMIN_DIVISION_PKEY = Indexes0.C_ADMIN_DIVISION_PKEY;
    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index PK_T_ARMS = Indexes0.PK_T_ARMS;
    public static final Index PK_T_ARMS_ATTACHMENT = Indexes0.PK_T_ARMS_ATTACHMENT;
    public static final Index PK_T_DATA_DOWNLOAD = Indexes0.PK_T_DATA_DOWNLOAD;
    public static final Index PK_T_DEPART = Indexes0.PK_T_DEPART;
    public static final Index T_DIVISION_PKEY = Indexes0.T_DIVISION_PKEY;
    public static final Index PK_T_EQUIP_TYPE = Indexes0.PK_T_EQUIP_TYPE;
    public static final Index PK_T_EQUIPMENT = Indexes0.PK_T_EQUIPMENT;
    public static final Index PK_T_FILE = Indexes0.PK_T_FILE;
    public static final Index PK_T_INDUSTRY = Indexes0.PK_T_INDUSTRY;
    public static final Index PK_T_LINK = Indexes0.PK_T_LINK;
    public static final Index PK_T_MANAGEMENT_REGULATION = Indexes0.PK_T_MANAGEMENT_REGULATION;
    public static final Index PK_T_MANAGEMENT_REGULATION_ATTACHMENT = Indexes0.PK_T_MANAGEMENT_REGULATION_ATTACHMENT;
    public static final Index PK__MARKET_INFORMATION = Indexes0.PK__MARKET_INFORMATION;
    public static final Index PK_T_MARKET_INFORMATION_ATTACHMENT = Indexes0.PK_T_MARKET_INFORMATION_ATTACHMENT;
    public static final Index PK_T_MESSAGE = Indexes0.PK_T_MESSAGE;
    public static final Index PK_T_NEWS = Indexes0.PK_T_NEWS;
    public static final Index PK_T_NEWS_ATTACHMENT = Indexes0.PK_T_NEWS_ATTACHMENT;
    public static final Index PK_T_NOTICE = Indexes0.PK_T_NOTICE;
    public static final Index PK_T_NOTICE_ATTACHMENT = Indexes0.PK_T_NOTICE_ATTACHMENT;
    public static final Index PK_T_ORDERING_MEALS = Indexes0.PK_T_ORDERING_MEALS;
    public static final Index PK_T_PARTY = Indexes0.PK_T_PARTY;
    public static final Index PK_T_PARTY_ATTACHMENT = Indexes0.PK_T_PARTY_ATTACHMENT;
    public static final Index PK_T_QUALITY_DEAL = Indexes0.PK_T_QUALITY_DEAL;
    public static final Index PK_T_QUALITY_EVENT = Indexes0.PK_T_QUALITY_EVENT;
    public static final Index PK_T_QUALITY_NOTICE = Indexes0.PK_T_QUALITY_NOTICE;
    public static final Index PK_T_QUALITY_NOTICE_ATTACHMENT = Indexes0.PK_T_QUALITY_NOTICE_ATTACHMENT;
    public static final Index PK_T_REPORTS = Indexes0.PK_T_REPORTS;
    public static final Index PK_T_ROLE = Indexes0.PK_T_ROLE;
    public static final Index PK_T_ROOM_RESERVATION = Indexes0.PK_T_ROOM_RESERVATION;
    public static final Index PK_T_SUBJECT = Indexes0.PK_T_SUBJECT;
    public static final Index PK_T_SUPPLIER = Indexes0.PK_T_SUPPLIER;
    public static final Index PK_T_SUPPLIER_TYPE = Indexes0.PK_T_SUPPLIER_TYPE;
    public static final Index PK_T_SYSTEM_NOTICE = Indexes0.PK_T_SYSTEM_NOTICE;
    public static final Index T_SYSTEMLOG_PKEY = Indexes0.T_SYSTEMLOG_PKEY;
    public static final Index PK_T_TENDER_ORGATION = Indexes0.PK_T_TENDER_ORGATION;
    public static final Index PK_T_USER = Indexes0.PK_T_USER;
    public static final Index PK_T_VEHICLE_PICK = Indexes0.PK_T_VEHICLE_PICK;
    public static final Index PK_T_WORK_DYNAMICS = Indexes0.PK_T_WORK_DYNAMICS;
    public static final Index PK_T_WORK_DYNAMICS_ATTACHMENT = Indexes0.PK_T_WORK_DYNAMICS_ATTACHMENT;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index C_ADMIN_DIVISION_PKEY = Internal.createIndex("c_admin_division_pkey", CAdminDivision.C_ADMIN_DIVISION, new OrderField[] { CAdminDivision.C_ADMIN_DIVISION.ID }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index PK_T_ARMS = Internal.createIndex("pk_t_arms", TArms.T_ARMS, new OrderField[] { TArms.T_ARMS.ID }, true);
        public static Index PK_T_ARMS_ATTACHMENT = Internal.createIndex("pk_t_arms_attachment", TArmsAttachment.T_ARMS_ATTACHMENT, new OrderField[] { TArmsAttachment.T_ARMS_ATTACHMENT.ID }, true);
        public static Index PK_T_DATA_DOWNLOAD = Internal.createIndex("pk_t_data_download", TDataDownload.T_DATA_DOWNLOAD, new OrderField[] { TDataDownload.T_DATA_DOWNLOAD.ID }, true);
        public static Index PK_T_DEPART = Internal.createIndex("pk_t_depart", TDepart.T_DEPART, new OrderField[] { TDepart.T_DEPART.ID }, true);
        public static Index T_DIVISION_PKEY = Internal.createIndex("t_division_pkey", TDivision.T_DIVISION, new OrderField[] { TDivision.T_DIVISION.ID }, true);
        public static Index PK_T_EQUIP_TYPE = Internal.createIndex("pk_t_equip_type", TEquipType.T_EQUIP_TYPE, new OrderField[] { TEquipType.T_EQUIP_TYPE.ID }, true);
        public static Index PK_T_EQUIPMENT = Internal.createIndex("pk_t_equipment", TEquipment.T_EQUIPMENT, new OrderField[] { TEquipment.T_EQUIPMENT.ID }, true);
        public static Index PK_T_FILE = Internal.createIndex("pk_t_file", TFile.T_FILE, new OrderField[] { TFile.T_FILE.ID }, true);
        public static Index PK_T_INDUSTRY = Internal.createIndex("pk_t_industry", TIndustry.T_INDUSTRY, new OrderField[] { TIndustry.T_INDUSTRY.ID }, true);
        public static Index PK_T_LINK = Internal.createIndex("pk_t_link", TLink.T_LINK, new OrderField[] { TLink.T_LINK.ID }, true);
        public static Index PK_T_MANAGEMENT_REGULATION = Internal.createIndex("pk_t_management_regulation", TManagementRegulation.T_MANAGEMENT_REGULATION, new OrderField[] { TManagementRegulation.T_MANAGEMENT_REGULATION.ID }, true);
        public static Index PK_T_MANAGEMENT_REGULATION_ATTACHMENT = Internal.createIndex("pk_t_management_regulation_attachment", TManagementRegulationAttachment.T_MANAGEMENT_REGULATION_ATTACHMENT, new OrderField[] { TManagementRegulationAttachment.T_MANAGEMENT_REGULATION_ATTACHMENT.ID }, true);
        public static Index PK__MARKET_INFORMATION = Internal.createIndex("pk__market_information", TMarketInformation.T_MARKET_INFORMATION, new OrderField[] { TMarketInformation.T_MARKET_INFORMATION.ID }, true);
        public static Index PK_T_MARKET_INFORMATION_ATTACHMENT = Internal.createIndex("pk_t_market_information_attachment", TMarketInformationAttachment.T_MARKET_INFORMATION_ATTACHMENT, new OrderField[] { TMarketInformationAttachment.T_MARKET_INFORMATION_ATTACHMENT.ID }, true);
        public static Index PK_T_MESSAGE = Internal.createIndex("pk_t_message", TMessage.T_MESSAGE, new OrderField[] { TMessage.T_MESSAGE.ID }, true);
        public static Index PK_T_NEWS = Internal.createIndex("pk_t_news", TNews.T_NEWS, new OrderField[] { TNews.T_NEWS.ID }, true);
        public static Index PK_T_NEWS_ATTACHMENT = Internal.createIndex("pk_t_news_attachment", TNewsAttachment.T_NEWS_ATTACHMENT, new OrderField[] { TNewsAttachment.T_NEWS_ATTACHMENT.ID }, true);
        public static Index PK_T_NOTICE = Internal.createIndex("pk_t_notice", TNotice.T_NOTICE, new OrderField[] { TNotice.T_NOTICE.ID }, true);
        public static Index PK_T_NOTICE_ATTACHMENT = Internal.createIndex("pk_t_notice_attachment", TNoticeAttachment.T_NOTICE_ATTACHMENT, new OrderField[] { TNoticeAttachment.T_NOTICE_ATTACHMENT.ID }, true);
        public static Index PK_T_ORDERING_MEALS = Internal.createIndex("pk_t_ordering_meals", TOrderingMeals.T_ORDERING_MEALS, new OrderField[] { TOrderingMeals.T_ORDERING_MEALS.ID }, true);
        public static Index PK_T_PARTY = Internal.createIndex("pk_t_party", TParty.T_PARTY, new OrderField[] { TParty.T_PARTY.ID }, true);
        public static Index PK_T_PARTY_ATTACHMENT = Internal.createIndex("pk_t_party_attachment", TPartyAttachment.T_PARTY_ATTACHMENT, new OrderField[] { TPartyAttachment.T_PARTY_ATTACHMENT.ID }, true);
        public static Index PK_T_QUALITY_DEAL = Internal.createIndex("pk_t_quality_deal", TQualityDeal.T_QUALITY_DEAL, new OrderField[] { TQualityDeal.T_QUALITY_DEAL.ID }, true);
        public static Index PK_T_QUALITY_EVENT = Internal.createIndex("pk_t_quality_event", TQualityEvent.T_QUALITY_EVENT, new OrderField[] { TQualityEvent.T_QUALITY_EVENT.ID }, true);
        public static Index PK_T_QUALITY_NOTICE = Internal.createIndex("pk_t_quality_notice", TQualityNotice.T_QUALITY_NOTICE, new OrderField[] { TQualityNotice.T_QUALITY_NOTICE.ID }, true);
        public static Index PK_T_QUALITY_NOTICE_ATTACHMENT = Internal.createIndex("pk_t_quality_notice_attachment", TQualityNoticeAttachment.T_QUALITY_NOTICE_ATTACHMENT, new OrderField[] { TQualityNoticeAttachment.T_QUALITY_NOTICE_ATTACHMENT.ID }, true);
        public static Index PK_T_REPORTS = Internal.createIndex("pk_t_reports", TReports.T_REPORTS, new OrderField[] { TReports.T_REPORTS.ID }, true);
        public static Index PK_T_ROLE = Internal.createIndex("pk_t_role", TRole.T_ROLE, new OrderField[] { TRole.T_ROLE.ID }, true);
        public static Index PK_T_ROOM_RESERVATION = Internal.createIndex("pk_t_room_reservation", TRoomReservation.T_ROOM_RESERVATION, new OrderField[] { TRoomReservation.T_ROOM_RESERVATION.ID }, true);
        public static Index PK_T_SUBJECT = Internal.createIndex("pk_t_subject", TSubject.T_SUBJECT, new OrderField[] { TSubject.T_SUBJECT.ID }, true);
        public static Index PK_T_SUPPLIER = Internal.createIndex("pk_t_supplier", TSupplier.T_SUPPLIER, new OrderField[] { TSupplier.T_SUPPLIER.ID }, true);
        public static Index PK_T_SUPPLIER_TYPE = Internal.createIndex("pk_t_supplier_type", TSupplierType.T_SUPPLIER_TYPE, new OrderField[] { TSupplierType.T_SUPPLIER_TYPE.ID }, true);
        public static Index PK_T_SYSTEM_NOTICE = Internal.createIndex("pk_t_system_notice", TSystemNotice.T_SYSTEM_NOTICE, new OrderField[] { TSystemNotice.T_SYSTEM_NOTICE.ID }, true);
        public static Index T_SYSTEMLOG_PKEY = Internal.createIndex("t_systemlog_pkey", TSystemlog.T_SYSTEMLOG, new OrderField[] { TSystemlog.T_SYSTEMLOG.ID }, true);
        public static Index PK_T_TENDER_ORGATION = Internal.createIndex("pk_t_tender_orgation", TTenderOrgation.T_TENDER_ORGATION, new OrderField[] { TTenderOrgation.T_TENDER_ORGATION.ID }, true);
        public static Index PK_T_USER = Internal.createIndex("pk_t_user", TUser.T_USER, new OrderField[] { TUser.T_USER.ID }, true);
        public static Index PK_T_VEHICLE_PICK = Internal.createIndex("pk_t_vehicle_pick", TVehiclePick.T_VEHICLE_PICK, new OrderField[] { TVehiclePick.T_VEHICLE_PICK.ID }, true);
        public static Index PK_T_WORK_DYNAMICS = Internal.createIndex("pk_t_work_dynamics", TWorkDynamics.T_WORK_DYNAMICS, new OrderField[] { TWorkDynamics.T_WORK_DYNAMICS.ID }, true);
        public static Index PK_T_WORK_DYNAMICS_ATTACHMENT = Internal.createIndex("pk_t_work_dynamics_attachment", TWorkDynamicsAttachment.T_WORK_DYNAMICS_ATTACHMENT, new OrderField[] { TWorkDynamicsAttachment.T_WORK_DYNAMICS_ATTACHMENT.ID }, true);
    }
}
