/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq;


import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.poem.jooq.tables.FlywaySchemaHistory;
import org.poem.jooq.tables.TArms;
import org.poem.jooq.tables.TDataDownload;
import org.poem.jooq.tables.TDepart;
import org.poem.jooq.tables.TEquipType;
import org.poem.jooq.tables.TEquipment;
import org.poem.jooq.tables.TFile;
import org.poem.jooq.tables.TIndustry;
import org.poem.jooq.tables.TLink;
import org.poem.jooq.tables.TManagementRegulation;
import org.poem.jooq.tables.TMarketInformation;
import org.poem.jooq.tables.TMessage;
import org.poem.jooq.tables.TNews;
import org.poem.jooq.tables.TOrderingMeals;
import org.poem.jooq.tables.TParty;
import org.poem.jooq.tables.TQualityDeal;
import org.poem.jooq.tables.TQualityEvent;
import org.poem.jooq.tables.TQualityNotice;
import org.poem.jooq.tables.TReports;
import org.poem.jooq.tables.TRole;
import org.poem.jooq.tables.TRoomReservation;
import org.poem.jooq.tables.TSubject;
import org.poem.jooq.tables.TSupplier;
import org.poem.jooq.tables.TSupplierType;
import org.poem.jooq.tables.TTenderOrgation;
import org.poem.jooq.tables.TUser;
import org.poem.jooq.tables.TVehiclePick;
import org.poem.jooq.tables.TWorkDynamics;
import org.poem.jooq.tables.records.FlywaySchemaHistoryRecord;
import org.poem.jooq.tables.records.TArmsRecord;
import org.poem.jooq.tables.records.TDataDownloadRecord;
import org.poem.jooq.tables.records.TDepartRecord;
import org.poem.jooq.tables.records.TEquipTypeRecord;
import org.poem.jooq.tables.records.TEquipmentRecord;
import org.poem.jooq.tables.records.TFileRecord;
import org.poem.jooq.tables.records.TIndustryRecord;
import org.poem.jooq.tables.records.TLinkRecord;
import org.poem.jooq.tables.records.TManagementRegulationRecord;
import org.poem.jooq.tables.records.TMarketInformationRecord;
import org.poem.jooq.tables.records.TMessageRecord;
import org.poem.jooq.tables.records.TNewsRecord;
import org.poem.jooq.tables.records.TOrderingMealsRecord;
import org.poem.jooq.tables.records.TPartyRecord;
import org.poem.jooq.tables.records.TQualityDealRecord;
import org.poem.jooq.tables.records.TQualityEventRecord;
import org.poem.jooq.tables.records.TQualityNoticeRecord;
import org.poem.jooq.tables.records.TReportsRecord;
import org.poem.jooq.tables.records.TRoleRecord;
import org.poem.jooq.tables.records.TRoomReservationRecord;
import org.poem.jooq.tables.records.TSubjectRecord;
import org.poem.jooq.tables.records.TSupplierRecord;
import org.poem.jooq.tables.records.TSupplierTypeRecord;
import org.poem.jooq.tables.records.TTenderOrgationRecord;
import org.poem.jooq.tables.records.TUserRecord;
import org.poem.jooq.tables.records.TVehiclePickRecord;
import org.poem.jooq.tables.records.TWorkDynamicsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<TArmsRecord> PK_T_ARMS = UniqueKeys0.PK_T_ARMS;
    public static final UniqueKey<TDataDownloadRecord> PK_T_DATA_DOWNLOAD = UniqueKeys0.PK_T_DATA_DOWNLOAD;
    public static final UniqueKey<TDepartRecord> PK_T_DEPART = UniqueKeys0.PK_T_DEPART;
    public static final UniqueKey<TEquipTypeRecord> PK_T_EQUIP_TYPE = UniqueKeys0.PK_T_EQUIP_TYPE;
    public static final UniqueKey<TEquipmentRecord> PK_T_EQUIPMENT = UniqueKeys0.PK_T_EQUIPMENT;
    public static final UniqueKey<TFileRecord> PK_T_FILE = UniqueKeys0.PK_T_FILE;
    public static final UniqueKey<TIndustryRecord> PK_T_INDUSTRY = UniqueKeys0.PK_T_INDUSTRY;
    public static final UniqueKey<TLinkRecord> PK_T_LINK = UniqueKeys0.PK_T_LINK;
    public static final UniqueKey<TManagementRegulationRecord> PK_T_MANAGEMENT_REGULATION = UniqueKeys0.PK_T_MANAGEMENT_REGULATION;
    public static final UniqueKey<TMarketInformationRecord> PK__MARKET_INFORMATION = UniqueKeys0.PK__MARKET_INFORMATION;
    public static final UniqueKey<TMessageRecord> PK_T_MESSAGE = UniqueKeys0.PK_T_MESSAGE;
    public static final UniqueKey<TNewsRecord> PK_T_NEWS = UniqueKeys0.PK_T_NEWS;
    public static final UniqueKey<TOrderingMealsRecord> PK_T_ORDERING_MEALS = UniqueKeys0.PK_T_ORDERING_MEALS;
    public static final UniqueKey<TPartyRecord> PK_T_PARTY = UniqueKeys0.PK_T_PARTY;
    public static final UniqueKey<TQualityDealRecord> PK_T_QUALITY_DEAL = UniqueKeys0.PK_T_QUALITY_DEAL;
    public static final UniqueKey<TQualityEventRecord> PK_T_QUALITY_EVENT = UniqueKeys0.PK_T_QUALITY_EVENT;
    public static final UniqueKey<TQualityNoticeRecord> PK_T_QUALITY_NOTICE = UniqueKeys0.PK_T_QUALITY_NOTICE;
    public static final UniqueKey<TReportsRecord> PK_T_REPORTS = UniqueKeys0.PK_T_REPORTS;
    public static final UniqueKey<TRoleRecord> PK_T_ROLE = UniqueKeys0.PK_T_ROLE;
    public static final UniqueKey<TRoomReservationRecord> PK_T_ROOM_RESERVATION = UniqueKeys0.PK_T_ROOM_RESERVATION;
    public static final UniqueKey<TSubjectRecord> PK_T_SUBJECT = UniqueKeys0.PK_T_SUBJECT;
    public static final UniqueKey<TSupplierRecord> PK_T_SUPPLIER = UniqueKeys0.PK_T_SUPPLIER;
    public static final UniqueKey<TSupplierTypeRecord> PK_T_SUPPLIER_TYPE = UniqueKeys0.PK_T_SUPPLIER_TYPE;
    public static final UniqueKey<TTenderOrgationRecord> PK_T_TENDER_ORGATION = UniqueKeys0.PK_T_TENDER_ORGATION;
    public static final UniqueKey<TUserRecord> PK_T_USER = UniqueKeys0.PK_T_USER;
    public static final UniqueKey<TVehiclePickRecord> PK_T_VEHICLE_PICK = UniqueKeys0.PK_T_VEHICLE_PICK;
    public static final UniqueKey<TWorkDynamicsRecord> PK_T_WORK_DYNAMICS = UniqueKeys0.PK_T_WORK_DYNAMICS;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<TArmsRecord> PK_T_ARMS = Internal.createUniqueKey(TArms.T_ARMS, "pk_t_arms", TArms.T_ARMS.ID);
        public static final UniqueKey<TDataDownloadRecord> PK_T_DATA_DOWNLOAD = Internal.createUniqueKey(TDataDownload.T_DATA_DOWNLOAD, "pk_t_data_download", TDataDownload.T_DATA_DOWNLOAD.ID);
        public static final UniqueKey<TDepartRecord> PK_T_DEPART = Internal.createUniqueKey(TDepart.T_DEPART, "pk_t_depart", TDepart.T_DEPART.ID);
        public static final UniqueKey<TEquipTypeRecord> PK_T_EQUIP_TYPE = Internal.createUniqueKey(TEquipType.T_EQUIP_TYPE, "pk_t_equip_type", TEquipType.T_EQUIP_TYPE.ID);
        public static final UniqueKey<TEquipmentRecord> PK_T_EQUIPMENT = Internal.createUniqueKey(TEquipment.T_EQUIPMENT, "pk_t_equipment", TEquipment.T_EQUIPMENT.ID);
        public static final UniqueKey<TFileRecord> PK_T_FILE = Internal.createUniqueKey(TFile.T_FILE, "pk_t_file", TFile.T_FILE.ID);
        public static final UniqueKey<TIndustryRecord> PK_T_INDUSTRY = Internal.createUniqueKey(TIndustry.T_INDUSTRY, "pk_t_industry", TIndustry.T_INDUSTRY.ID);
        public static final UniqueKey<TLinkRecord> PK_T_LINK = Internal.createUniqueKey(TLink.T_LINK, "pk_t_link", TLink.T_LINK.ID);
        public static final UniqueKey<TManagementRegulationRecord> PK_T_MANAGEMENT_REGULATION = Internal.createUniqueKey(TManagementRegulation.T_MANAGEMENT_REGULATION, "pk_t_management_regulation", TManagementRegulation.T_MANAGEMENT_REGULATION.ID);
        public static final UniqueKey<TMarketInformationRecord> PK__MARKET_INFORMATION = Internal.createUniqueKey(TMarketInformation.T_MARKET_INFORMATION, "pk__market_information", TMarketInformation.T_MARKET_INFORMATION.ID);
        public static final UniqueKey<TMessageRecord> PK_T_MESSAGE = Internal.createUniqueKey(TMessage.T_MESSAGE, "pk_t_message", TMessage.T_MESSAGE.ID);
        public static final UniqueKey<TNewsRecord> PK_T_NEWS = Internal.createUniqueKey(TNews.T_NEWS, "pk_t_news", TNews.T_NEWS.ID);
        public static final UniqueKey<TOrderingMealsRecord> PK_T_ORDERING_MEALS = Internal.createUniqueKey(TOrderingMeals.T_ORDERING_MEALS, "pk_t_ordering_meals", TOrderingMeals.T_ORDERING_MEALS.ID);
        public static final UniqueKey<TPartyRecord> PK_T_PARTY = Internal.createUniqueKey(TParty.T_PARTY, "pk_t_party", TParty.T_PARTY.ID);
        public static final UniqueKey<TQualityDealRecord> PK_T_QUALITY_DEAL = Internal.createUniqueKey(TQualityDeal.T_QUALITY_DEAL, "pk_t_quality_deal", TQualityDeal.T_QUALITY_DEAL.ID);
        public static final UniqueKey<TQualityEventRecord> PK_T_QUALITY_EVENT = Internal.createUniqueKey(TQualityEvent.T_QUALITY_EVENT, "pk_t_quality_event", TQualityEvent.T_QUALITY_EVENT.ID);
        public static final UniqueKey<TQualityNoticeRecord> PK_T_QUALITY_NOTICE = Internal.createUniqueKey(TQualityNotice.T_QUALITY_NOTICE, "pk_t_quality_notice", TQualityNotice.T_QUALITY_NOTICE.ID);
        public static final UniqueKey<TReportsRecord> PK_T_REPORTS = Internal.createUniqueKey(TReports.T_REPORTS, "pk_t_reports", TReports.T_REPORTS.ID);
        public static final UniqueKey<TRoleRecord> PK_T_ROLE = Internal.createUniqueKey(TRole.T_ROLE, "pk_t_role", TRole.T_ROLE.ID);
        public static final UniqueKey<TRoomReservationRecord> PK_T_ROOM_RESERVATION = Internal.createUniqueKey(TRoomReservation.T_ROOM_RESERVATION, "pk_t_room_reservation", TRoomReservation.T_ROOM_RESERVATION.ID);
        public static final UniqueKey<TSubjectRecord> PK_T_SUBJECT = Internal.createUniqueKey(TSubject.T_SUBJECT, "pk_t_subject", TSubject.T_SUBJECT.ID);
        public static final UniqueKey<TSupplierRecord> PK_T_SUPPLIER = Internal.createUniqueKey(TSupplier.T_SUPPLIER, "pk_t_supplier", TSupplier.T_SUPPLIER.ID);
        public static final UniqueKey<TSupplierTypeRecord> PK_T_SUPPLIER_TYPE = Internal.createUniqueKey(TSupplierType.T_SUPPLIER_TYPE, "pk_t_supplier_type", TSupplierType.T_SUPPLIER_TYPE.ID);
        public static final UniqueKey<TTenderOrgationRecord> PK_T_TENDER_ORGATION = Internal.createUniqueKey(TTenderOrgation.T_TENDER_ORGATION, "pk_t_tender_orgation", TTenderOrgation.T_TENDER_ORGATION.ID);
        public static final UniqueKey<TUserRecord> PK_T_USER = Internal.createUniqueKey(TUser.T_USER, "pk_t_user", TUser.T_USER.ID);
        public static final UniqueKey<TVehiclePickRecord> PK_T_VEHICLE_PICK = Internal.createUniqueKey(TVehiclePick.T_VEHICLE_PICK, "pk_t_vehicle_pick", TVehiclePick.T_VEHICLE_PICK.ID);
        public static final UniqueKey<TWorkDynamicsRecord> PK_T_WORK_DYNAMICS = Internal.createUniqueKey(TWorkDynamics.T_WORK_DYNAMICS, "pk_t_work_dynamics", TWorkDynamics.T_WORK_DYNAMICS.ID);
    }
}
